import { world, system } from "@minecraft/server";
import { IslandGenerator } from "./worldgen/IslandGenerator.js";
import { installBulkTerrainRuntime } from "./worldgen/BulkTerrainRuntime.js";
import { JigsawRegistry } from "./worldgen/JigsawRegistry.js";
import { StructureSetRuntime } from "./worldgen/StructureSetRuntime.js";
import { StructurePlacementCoordinator } from "./worldgen/StructurePlacementCoordinator.js";
import { StructurePlacementQueue } from "./worldgen/StructurePlacementQueue.js";
import { getGeneratedJigsawData } from "./worldgen/JigsawDataLoader.js";
import { StructureDensityField } from "./worldgen/StructureDensityField.js";
import { WorldgenJigsawRuntime } from "./worldgen/WorldgenJigsawRuntime.js";
import { runWorldgenSelfTest } from "./worldgen/WorldgenSelfTest.js";

const DIMENSION_ID="sky_archipelago:archipelago";
const FIND_ISLAND_MAX_RADIUS=98304;
const FIND_ISLAND_CELL_STEP=128;
const FIND_ISLAND_MAX_CELLS=8192;
const FIND_ISLAND_BATCH=2;
const FIND_ISLAND_MIN_COVERAGE=-0.02;
const generator=new IslandGenerator();
let bulkTerrain=null,structureSets=null,placementCoordinator=null,placementQueue=null,worldgen=null,lastTickStats=null,startupSelfTest=null;
let structureProcessBusy=false,placementProcessBusy=false,findIslandJob=null;
function archipelago(){return world.getDimension(DIMENSION_ID);}
function registry(){return new JigsawRegistry(getGeneratedJigsawData());}
function buildRuntime(){const data=getGeneratedJigsawData(),jigsawRegistry=new JigsawRegistry(data),densityField=new StructureDensityField();placementCoordinator=new StructurePlacementCoordinator(generator,{registry:jigsawRegistry,terrainOptions:{minY:-64,maxY:320},densityField});placementQueue=new StructurePlacementQueue({maxPerTick:1,maxRetries:3,retryDelay:20});structureSets=new StructureSetRuntime(generator,{data,registry:jigsawRegistry,dimensionId:DIMENSION_ID,radius:128,maxPlansPerTick:1,maxPlacementsPerTick:1,placementCoordinator,placementQueue,densityField});worldgen=new WorldgenJigsawRuntime(archipelago(),{data,registry:jigsawRegistry,generator,structureSets,densityField,placementCoordinator,placementQueue});structureSets.refresh(jigsawRegistry);}
system.beforeEvents.startup.subscribe(event=>{event.dimensionRegistry.registerCustomDimension(DIMENSION_ID);});
function runStartupSelfTest(){try{const test=runWorldgenSelfTest({data:getGeneratedJigsawData(),registry:worldgen?.registry,seed:generator.layoutSeed,deep:false});startupSelfTest=test;if(!test.ok)console.warn(`[Sky Archipelago] worldgen self-test errors: ${test.errors.join(" | ")}`);if(test.warnings.length)console.warn(`[Sky Archipelago] worldgen self-test warnings: ${test.warnings.slice(0,12).join(" | ")}`);}catch(error){startupSelfTest={ok:false,errors:[String(error)],warnings:[],snapshot:worldgen?.registry?.snapshot?.()??{}};console.warn(`[Sky Archipelago] worldgen self-test failed: ${error}`);}}
function makeSearchCells(x,z){const step=FIND_ISLAND_CELL_STEP,cx=Math.floor(x/step),cz=Math.floor(z/step),cells=[];for(let r=0;r<=Math.ceil(FIND_ISLAND_MAX_RADIUS/step);r++){for(let dx=-r;dx<=r;dx++){for(let dz=-r;dz<=r;dz++){if(Math.max(Math.abs(dx),Math.abs(dz))!==r)continue;const px=(cx+dx)*step+step/2,pz=(cz+dz)*step+step/2;if(Math.hypot(px-x,pz-z)<=FIND_ISLAND_MAX_RADIUS)cells.push({x:px,z:pz,distance:Math.hypot(px-x,pz-z)});if(cells.length>=FIND_ISLAND_MAX_CELLS)return cells;}}}return cells;}
function quickIslandProbe(px,pz){const ds=generator.descriptorsNear(px,pz);let best=null;for(const d of ds){const dx=px-d.x,dz=pz-d.z,reach=Math.max(d.maxR*1.5,Math.max(48,Math.max(Math.abs(d.hangX)+d.tailX*2,Math.abs(d.hangZ)+d.tailZ*2)));if(dx*dx+dz*dz>reach*reach)continue;const h=generator.shapeSample(d,px,pz);if(!h?.influence||h.coverage<FIND_ISLAND_MIN_COVERAGE)continue;const score=h.coverage-(Math.hypot(dx,dz)/Math.max(1,d.maxR))*0.15;if(!best||score>best.score)best={d,h,score};}return best;}
function surfaceAt(d,h,x,z){const top=Math.min(320,Math.ceil(d.y+d.plateau+48)),bottom=Math.max(-64,Math.floor(d.y-d.cliff-d.hang-32));if(generator.density.density(d,h,x,top,z)>0)return top;let y=top;for(;y>bottom;y-=8)if(generator.density.density(d,h,x,y,z)>0){let lo=Math.max(bottom,y-7),hi=y;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(generator.density.density(d,h,x,mid,z)>0)lo=mid;else hi=mid-1;}return lo;}return null;}
function* findIslandJobGenerator(job){while(findIslandJob===job&&!job.done){for(let n=0;n<FIND_ISLAND_BATCH&&job.index<job.cells.length;n++){const c=job.cells[job.index++];job.samples++;const probes=[[c.x,c.z],[c.x+64,c.z],[c.x-64,c.z],[c.x,c.z+64],[c.x,c.z-64]];for(const [px,pz] of probes){const hit=quickIslandProbe(px,pz);if(!hit)continue;const y=surfaceAt(hit.d,hit.h,px,pz);if(y==null)continue;job.result={x:Math.floor(px),y,z:Math.floor(pz),distance:Math.hypot(px-job.startX,pz-job.startZ),coverage:hit.h.coverage,samples:job.samples};job.done=true;findIslandJob=null;return;}}if(job.index>=job.cells.length){job.done=true;findIslandJob=null;return;}yield;}}
function finishIslandSearch(player,job){if(job.result){const r=job.result;generator.requestAround({location:{x:r.x,z:r.z},dimension:archipelago()});player.teleport({x:r.x+0.5,y:r.y+4,z:r.z+0.5},{dimension:archipelago()});player.sendMessage(`§aIsland found! §7X=${r.x} Y=${r.y} Z=${r.z} §8distance=${Math.round(r.distance)} coverage=${r.coverage.toFixed(3)} samples=${r.samples}`);}else player.sendMessage(`§cNo island found within ${FIND_ISLAND_MAX_RADIUS} blocks. Tested ${job.samples} coarse cells without blocking the server.`);}
function findAndTeleportIsland(player){if(findIslandJob){player.sendMessage("§eAn island search is already running.");return;}try{const startX=Math.floor(player.location.x),startZ=Math.floor(player.location.z),job={startX,startZ,cells:makeSearchCells(startX,startZ),index:0,samples:0,result:null,done:false,player};findIslandJob=job;player.sendMessage(`§7Fast island search started: ${job.cells.length} coarse cells, ${FIND_ISLAND_BATCH} cells/tick.`);system.runJob(findIslandJobGenerator(job));}catch(error){findIslandJob=null;player.sendMessage(`§cIsland search failed: ${error}`);console.warn(`[Sky Archipelago] island search failed: ${error}`);}}
world.afterEvents.worldLoad.subscribe(()=>{generator.load();generator.dimension=archipelago();bulkTerrain=installBulkTerrainRuntime(generator);buildRuntime();system.run(runStartupSelfTest);system.run(()=>{const test=startupSelfTest,snapshot=test?.snapshot??worldgen?.registry?.snapshot?.()??{};world.sendMessage(`§aSky Archipelago loaded. §7Worldgen: ${snapshot.pieces??0} pieces, ${snapshot.pools??0} pools, ${snapshot.structures??0} structures, ${snapshot.structureSets??0} sets.`);world.sendMessage(`§7Bulk terrain writer enabled: greedy cuboids + batched fillBlocks + stone variants + ore veins.`);});});
system.runInterval(()=>{if(findIslandJob?.done){const job=findIslandJob;findIslandJob=null;finishIslandSearch(job.player,job);}if(!structureSets||!worldgen)return;for(const player of world.getAllPlayers())if(player.dimension.id===DIMENSION_ID){generator.requestAround(player);structureSets.enqueueAround(player.location.x,player.location.z);}generator.tick();if(!structureProcessBusy){structureProcessBusy=true;structureSets.process().then(stats=>{lastTickStats=stats;}).catch(error=>console.warn(`[Sky Archipelago] structure-set runtime error: ${error}`)).finally(()=>{structureProcessBusy=false;});}if(placementQueue&&!placementProcessBusy){placementProcessBusy=true;placementQueue.process(placementCoordinator).catch(error=>console.warn(`[Sky Archipelago] placement queue error: ${error}`)).finally(()=>{placementProcessBusy=false;});}},1);
system.afterEvents.scriptEventReceive.subscribe(event=>{const player=event.sourceEntity;if(!player||player.typeId!=="minecraft:player")return;if(event.id==="sky_archipelago:enter"){player.teleport({x:0.5,y:120,z:0.5},{dimension:archipelago()});player.sendMessage("§bWelcome to Sky Archipelago.");return;}if(event.id==="sky_archipelago:find_island"){findAndTeleportIsland(player);return;}if(event.id==="sky_archipelago:lobby"){player.teleport({x:0.5,y:100,z:0.5},{dimension:world.getDimension("minecraft:overworld")});player.sendMessage("§eReturned to the Overworld lobby.");return;}if(event.id==="sky_archipelago:reset"){generator.reset();buildRuntime();player.sendMessage("§eSky Archipelago generation state reset. Existing blocks are not erased.");return;}if(event.id==="sky_archipelago:status"){const snapshot=worldgen?.snapshot?.()??{},native=generator.native?.snapshot?.(),bulk=bulkTerrain?.snapshot?.();player.sendMessage(`§bSky Archipelago §7| generated=${generator.generated?.size??0} queued=${generator.queue?.length??0} structureJobs=${generator.structureJobs?.length??0}`);player.sendMessage(`§7Sets=${snapshot.structureSets??0} | densityBoxes=${snapshot.densityBoxes??0} | junctions=${snapshot.densityJunctions??0} | pendingPlans=${structureSets?.pending?.length??0} | pendingPlacements=${placementQueue?.size?.()??0}`);player.sendMessage(`§7Bulk: chunks=${bulk?.chunks??0} fills=${bulk?.fills??0} singles=${bulk?.singles??0} variants=${bulk?.variants??0} failed=${bulk?.failed??0} pending=${bulk?.pendingChunks??0}`);player.sendMessage(`§7Last tick: ${JSON.stringify(lastTickStats??{})} | Native overlap records: ${native?.overlap?.length??0}`);return;}if(event.id==="sky_archipelago:test_worldgen"){try{const test=runWorldgenSelfTest({data:getGeneratedJigsawData(),registry:worldgen?.registry,seed:generator.layoutSeed,deep:true});player.sendMessage(`§bWorldgen self-test: ${test.ok?"§aPASS":"§cFAIL"}`);player.sendMessage(`§7Pieces=${test.snapshot.pieces} Pools=${test.snapshot.pools} Structures=${test.snapshot.structures} Sets=${test.snapshot.structureSets}`);if(test.warnings.length)player.sendMessage(`§eWarnings: ${test.warnings.slice(0,3).join(" | ")}`);if(test.errors.length)player.sendMessage(`§cErrors: ${test.errors.slice(0,3).join(" | ")}`);}catch(e){player.sendMessage(`§cWorldgen self-test exception: ${e}`);}return;}if(event.id==="sky_archipelago:refresh_structures"){try{const r=registry();generator.registry?.refresh?.();structureSets?.refresh?.(r);placementCoordinator?.refresh?.(r);worldgen?.refresh?.();player.sendMessage("§aStructure registries refreshed from generated jigsaw data.");}catch(e){player.sendMessage(`§cStructure registry refresh failed: ${e}`);}}});