import { world, system } from "@minecraft/server";
import { IslandGenerator } from "./worldgen/IslandGenerator.js";
import { installBulkTerrainRuntime } from "./worldgen/BulkTerrainRuntime.js";
import { JigsawRegistry } from "./worldgen/JigsawRegistry.js";
import { StructureSetRuntime } from "./worldgen/StructureSetRuntime.js";
import { StructurePlacementCoordinator } from "./worldgen/StructurePlacementCoordinator.js";
import { StructurePlacementQueue } from "./worldgen/StructurePlacementQueue.js";
import { getGeneratedJigsawData } from "./worldgen/JigsawDataLoader.js";
import { StructureDensityField } from "./worldgen/StructureDensityField.js";
import { WorldgenJigsawRuntime } from "./worldgen/WorldgenJigsawRuntime.js";
import { runWorldgenSelfTest } from "./worldgen/WorldgenSelfTest.js";

const DIMENSION_ID = "sky_archipelago:archipelago";
const FIND_ISLAND_MAX_RADIUS = 98304;
const FIND_ISLAND_STEP = 16;
const FIND_ISLAND_ANGLE_STEPS = 128;
const FIND_ISLAND_MAX_SAMPLES = 120000;
const generator = new IslandGenerator();
let bulkTerrain = null, structureSets = null, placementCoordinator = null, placementQueue = null, worldgen = null, lastTickStats = null, startupSelfTest = null;
let structureProcessBusy = false, placementProcessBusy = false;

function archipelago(){return world.getDimension(DIMENSION_ID);}
function registry(){return new JigsawRegistry(getGeneratedJigsawData());}
function buildRuntime(){const data=getGeneratedJigsawData(),jigsawRegistry=new JigsawRegistry(data),densityField=new StructureDensityField();placementCoordinator=new StructurePlacementCoordinator(generator,{registry:jigsawRegistry,terrainOptions:{minY:-64,maxY:320},densityField});placementQueue=new StructurePlacementQueue({maxPerTick:1,maxRetries:3,retryDelay:20});structureSets=new StructureSetRuntime(generator,{data,registry:jigsawRegistry,dimensionId:DIMENSION_ID,radius:128,maxPlansPerTick:1,maxPlacementsPerTick:1,placementCoordinator,placementQueue,densityField});worldgen=new WorldgenJigsawRuntime(archipelago(),{data,registry:jigsawRegistry,generator,structureSets,densityField,placementCoordinator,placementQueue});structureSets.refresh(jigsawRegistry);}
system.beforeEvents.startup.subscribe(event=>{event.dimensionRegistry.registerCustomDimension(DIMENSION_ID);});
function runStartupSelfTest(){try{const test=runWorldgenSelfTest({data:getGeneratedJigsawData(),registry:worldgen?.registry,seed:generator.layoutSeed,deep:false});startupSelfTest=test;if(!test.ok)console.warn(`[Sky Archipelago] worldgen self-test errors: ${test.errors.join(" | ")}`);if(test.warnings.length)console.warn(`[Sky Archipelago] worldgen self-test warnings: ${test.warnings.slice(0,12).join(" | ")}`);}catch(error){startupSelfTest={ok:false,errors:[String(error)],warnings:[],snapshot:worldgen?.registry?.snapshot?.()??{}};console.warn(`[Sky Archipelago] worldgen self-test failed: ${error}`);}}

function findNearestIsland(x,z,maxRadius=FIND_ISLAND_MAX_RADIUS){
 if(!generator.noise||!generator.clusters||!generator.factory||!generator.shape||!generator.density)throw new Error("Island generator is not initialized yet.");
 let samples=0;
 const test=(px,pz)=>{samples++;const descriptors=generator.descriptorsNear(px,pz);for(const d of descriptors){const dx=px-d.x,dz=pz-d.z,reach=Math.max(d.maxR*1.15,Math.max(32,Math.max(Math.abs(d.hangX)+d.tailX*1.5,Math.abs(d.hangZ)+d.tailZ*1.5)));if(dx*dx+dz*dz>reach*reach)continue;const h=generator.shapeSample(d,px,pz);if(!h.influence||h.coverage<=-.05)continue;const top=Math.min(320,Math.ceil(d.y+d.plateau+96)),bottom=Math.max(-64,Math.floor(d.y-d.cliff-d.hang-96));for(let y=top;y>=bottom;y--){if(generator.density.density(d,h,px,y,pz)>0)return{x:Math.floor(px),z:Math.floor(pz),y,distance:Math.hypot(px-x,pz-z),coverage:h.coverage,descriptor:d};}}return null;};
 const origin=test(Math.floor(x),Math.floor(z));if(origin)return{...origin,samples};
 for(let radius=FIND_ISLAND_STEP;radius<=maxRadius&&samples<FIND_ISLAND_MAX_SAMPLES;radius+=FIND_ISLAND_STEP){const circumference=Math.max(8,Math.min(FIND_ISLAND_ANGLE_STEPS,Math.ceil(2*Math.PI*radius/FIND_ISLAND_STEP)));for(let i=0;i<circumference&&samples<FIND_ISLAND_MAX_SAMPLES;i++){const a=2*Math.PI*i/circumference,result=test(Math.floor(x+Math.cos(a)*radius),Math.floor(z+Math.sin(a)*radius));if(result)return{...result,samples};}}
 return null;
}
function findAndTeleportIsland(player){try{const start={x:Math.floor(player.location.x),z:Math.floor(player.location.z)};player.sendMessage("§7Searching the island noise field...");const result=findNearestIsland(start.x,start.z);if(!result){player.sendMessage(`§cNo island found within ${FIND_ISLAND_MAX_RADIUS} blocks after ${FIND_ISLAND_MAX_SAMPLES} noise samples.`);return;}generator.requestAround({location:{x:result.x,z:result.z},dimension:archipelago()});player.teleport({x:result.x+0.5,y:result.y+4,z:result.z+0.5},{dimension:archipelago()});player.sendMessage(`§aNearest island found! §7X=${result.x} Y=${result.y} Z=${result.z} §8distance=${Math.round(result.distance)} samples=${result.samples}`);}catch(error){player.sendMessage(`§cIsland noise search failed: ${error}`);console.warn(`[Sky Archipelago] island noise search failed: ${error}`);}}

world.afterEvents.worldLoad.subscribe(()=>{generator.load();generator.dimension=archipelago();bulkTerrain=installBulkTerrainRuntime(generator);buildRuntime();system.run(runStartupSelfTest);system.run(()=>{const test=startupSelfTest,snapshot=test?.snapshot??worldgen?.registry?.snapshot?.()??{};world.sendMessage(`§aSky Archipelago loaded. §7Worldgen: ${snapshot.pieces??0} pieces, ${snapshot.pools??0} pools, ${snapshot.structures??0} structures, ${snapshot.structureSets??0} sets.`);world.sendMessage(`§7Bulk terrain writer enabled: greedy cuboids + batched fillBlocks + stone variants + ore veins.`);});});
system.runInterval(()=>{if(!structureSets||!worldgen)return;for(const player of world.getAllPlayers())if(player.dimension.id===DIMENSION_ID){generator.requestAround(player);structureSets.enqueueAround(player.location.x,player.location.z);}generator.tick();if(!structureProcessBusy){structureProcessBusy=true;structureSets.process().then(stats=>{lastTickStats=stats;}).catch(error=>console.warn(`[Sky Archipelago] structure-set runtime error: ${error}`)).finally(()=>{structureProcessBusy=false;});}if(placementQueue&&!placementProcessBusy){placementProcessBusy=true;placementQueue.process(placementCoordinator).catch(error=>console.warn(`[Sky Archipelago] placement queue error: ${error}`)).finally(()=>{placementProcessBusy=false;});}},1);
system.afterEvents.scriptEventReceive.subscribe(event=>{const player=event.sourceEntity;if(!player||player.typeId!=="minecraft:player")return;if(event.id==="sky_archipelago:enter"){player.teleport({x:0.5,y:120,z:0.5},{dimension:archipelago()});player.sendMessage("§bWelcome to Sky Archipelago.");return;}if(event.id==="sky_archipelago:find_island"){findAndTeleportIsland(player);return;}if(event.id==="sky_archipelago:lobby"){player.teleport({x:0.5,y:100,z:0.5},{dimension:world.getDimension("minecraft:overworld")});player.sendMessage("§eReturned to the Overworld lobby.");return;}if(event.id==="sky_archipelago:reset"){generator.reset();buildRuntime();player.sendMessage("§eSky Archipelago generation state reset. Existing blocks are not erased.");return;}if(event.id==="sky_archipelago:status"){const snapshot=worldgen?.snapshot?.()??{},native=generator.native?.snapshot?.(),bulk=bulkTerrain?.snapshot?.();player.sendMessage(`§bSky Archipelago §7| generated=${generator.generated?.size??0} queued=${generator.queue?.length??0} structureJobs=${generator.structureJobs?.length??0}`);player.sendMessage(`§7Sets=${snapshot.structureSets??0} | densityBoxes=${snapshot.densityBoxes??0} | junctions=${snapshot.densityJunctions??0} | pendingPlans=${structureSets?.pending?.length??0} | pendingPlacements=${placementQueue?.size?.()??0}`);player.sendMessage(`§7Bulk: chunks=${bulk?.chunks??0} fills=${bulk?.fills??0} singles=${bulk?.singles??0} variants=${bulk?.variants??0} failed=${bulk?.failed??0} pending=${bulk?.pendingChunks??0}`);player.sendMessage(`§7Last tick: ${JSON.stringify(lastTickStats??{})} | Native overlap records: ${native?.overlap?.length??0}`);return;}if(event.id==="sky_archipelago:test_worldgen"){try{const test=runWorldgenSelfTest({data:getGeneratedJigsawData(),registry:worldgen?.registry,seed:generator.layoutSeed,deep:true});player.sendMessage(`§bWorldgen self-test: ${test.ok?"§aPASS":"§cFAIL"}`);player.sendMessage(`§7Pieces=${test.snapshot.pieces} Pools=${test.snapshot.pools} Structures=${test.snapshot.structures} Sets=${test.snapshot.structureSets}`);if(test.warnings.length)player.sendMessage(`§eWarnings: ${test.warnings.slice(0,3).join(" | ")}`);if(test.errors.length)player.sendMessage(`§cErrors: ${test.errors.slice(0,3).join(" | ")}`);}catch(e){player.sendMessage(`§cWorldgen self-test exception: ${e}`);}return;}if(event.id==="sky_archipelago:refresh_structures"){try{const r=registry();generator.registry?.refresh?.();structureSets?.refresh?.(r);placementCoordinator?.refresh?.(r);worldgen?.refresh?.();player.sendMessage("§aStructure registries refreshed from generated jigsaw data.");}catch(e){player.sendMessage(`§cStructure registry refresh failed: ${e}`);}}});