import { StructurePieceGraph } from "./StructurePieceModel.js";

export const VillagePieceKind=Object.freeze({CENTER:"CENTER",ROAD:"ROAD",BUILDING:"BUILDING",FARM:"FARM",OTHER:"OTHER"});
export class VillagePieceClassifier {
 classify(piece){const text=`${piece?.id??""} ${piece?.template??""} ${piece?.role??""}`.toLowerCase();if(["road","street","path","junction","crossing"].some(t=>text.includes(t)))return VillagePieceKind.ROAD;if(["farm","crop","field"].some(t=>text.includes(t)))return VillagePieceKind.FARM;if(["town","meeting","center","bell"].some(t=>text.includes(t)))return VillagePieceKind.CENTER;const b=piece?.bounds;if(!b)return VillagePieceKind.OTHER;const sx=b.max.x-b.min.x+1,sz=b.max.z-b.min.z+1,h=b.max.y-b.min.y+1,area=sx*sz;if((sx<=6&&sz>=16||sz<=6&&sx>=16)&&h<=5)return VillagePieceKind.ROAD;if(area>=64&&h<=3)return VillagePieceKind.FARM;return area>=20&&h>=4?VillagePieceKind.BUILDING:VillagePieceKind.OTHER;}
}
export class VillageIslandBoundsEvaluator {
 fits(host,b){const r=(host.usableRadius??host.radius??0),cx=host.x,cz=host.z;return [[b.min.x,b.min.z],[b.min.x,b.max.z],[b.max.x,b.min.z],[b.max.x,b.max.z]].every(([x,z])=>(x-cx)**2+(z-cz)**2<=r*r);}
 centerFits(host,b){const cx=(b.min.x+b.max.x)/2,cz=(b.min.z+b.max.z)/2,r=host.usableRadius??host.radius??0;return (cx-host.x)**2+(cz-host.z)**2<=r*r;}
 pieceFits(host,b,k){return k===VillagePieceKind.CENTER||k===VillagePieceKind.BUILDING?this.fits(host,b):this.centerFits(host,b);}
}
export class VillageLayoutTrimmer {
 constructor(){this.classifier=new VillagePieceClassifier();this.bounds=new VillageIslandBoundsEvaluator();}
 trim(pieces,host){let candidates=pieces.map((p,i)=>({piece:p,kind:this.classifier.classify(p),index:i}));const original=candidates.length;const priority={FARM:5,OTHER:4,BUILDING:3,ROAD:2,CENTER:1};while(candidates.length>1){const envelope=this.envelope(candidates);const piecesFit=candidates.every(c=>this.bounds.pieceFits(host,c.piece.bounds,c.kind)),boundsFit=envelope&&this.bounds.fits(host,envelope);if(piecesFit&&boundsFit)break;let drop=-1,best=null;for(let i=0;i<candidates.length;i++){const c=candidates[i];if(c.kind===VillagePieceKind.CENTER&&candidates.filter(x=>x.kind===VillagePieceKind.CENTER).length<=1)continue;if(c.kind===VillagePieceKind.BUILDING&&candidates.filter(x=>x.kind===VillagePieceKind.BUILDING).length<=1&&candidates.some(x=>x.kind===VillagePieceKind.CENTER))continue;const b=c.piece.bounds,dx=((b.min.x+b.max.x)/2)-host.x,dz=((b.min.z+b.max.z)/2)-host.z,score=priority[c.kind]*100000+dx*dx+dz*dz;if(best===null||score>best){best=score;drop=i;}}if(drop<0)break;candidates.splice(drop,1);}const retained=candidates.map(c=>c.piece),buildings=candidates.filter(c=>c.kind===VillagePieceKind.BUILDING).length,core=candidates.some(c=>c.kind===VillagePieceKind.CENTER);const tier=core&&retained.length===original&&retained.length>=6&&buildings>=3?"FULL":core&&retained.length>=3&&buildings>=1?"HAMLET":"REJECT";return{accepted:tier!=="REJECT",tier,stage:tier==="FULL"?(retained.length<original?"ground_village_v2_trimmed":"ground_village_v2_accepted"):tier==="HAMLET"?"ground_village_v2_downgraded_hamlet":"ground_village_v2_rejected_empty_after_trim",pieces:retained,removed:original-retained.length,bounds:this.envelope(candidates)};}
 envelope(items){if(!items.length)return null;let min={x:Infinity,y:Infinity,z:Infinity},max={x:-Infinity,y:-Infinity,z:-Infinity};for(const {piece} of items){const b=piece.bounds;min.x=Math.min(min.x,b.min.x);min.y=Math.min(min.y,b.min.y);min.z=Math.min(min.z,b.min.z);max.x=Math.max(max.x,b.max.x);max.y=Math.max(max.y,b.max.y);max.z=Math.max(max.z,b.max.z);}return{min,max};}
}
export class VillagePieceGraphAdapter {toGraph(pieces,origin){const g=new StructurePieceGraph("village",origin);for(const p of pieces)g.add(p);return g;}}
