package org.sathrek.sky_archipelago.config.settings;

import java.util.List;
import org.sathrek.sky_archipelago.config.ClusterSpacingMode;
import org.sathrek.sky_archipelago.config.IslandSizeBand;
import org.sathrek.sky_archipelago.config.IslandSizeMode;
import org.sathrek.sky_archipelago.config.OceanBlockType;
import org.sathrek.sky_archipelago.config.SkyIslandGeneratorSettings;
import org.sathrek.sky_archipelago.config.SkyIslandSettings;
import org.sathrek.sky_archipelago.config.TerrainOverlapMode;
import org.sathrek.sky_archipelago.worldgen.structure.StructurePlacementPolicy;
import org.sathrek.sky_archipelago.worldgen.structure.StructureWhitelist;

public final class SkyIslandSettingsFactory {
   private SkyIslandSettingsFactory() {
   }

   public static SkyIslandGeneratorSettings generator(
      double islandDensity,
      int minIslandRadius,
      int maxIslandRadius,
      IslandSizeMode islandSizeMode,
      IslandSizeBand smallIslandSizeBand,
      IslandSizeBand mediumIslandSizeBand,
      IslandSizeBand largeIslandSizeBand,
      int minIslandY,
      int maxIslandY,
      double lowBandWeight,
      double midHighBandWeight,
      double veryHighBandWeight,
      int lowBandCenterOffset,
      int veryHighBandCenterOffset,
      int clusterSpacing,
      double terrainReliefScale,
      boolean classicArchetypeEnabled,
      double classicArchetypeWeight,
      boolean bowlCraterArchetypeEnabled,
      double bowlCraterArchetypeWeight,
      boolean crescentArchetypeEnabled,
      double crescentArchetypeWeight,
      boolean terraceArchetypeEnabled,
      double terraceArchetypeWeight,
      boolean oceanEnabled,
      int oceanLevelY,
      OceanBlockType oceanBlockType,
      int supportCheckDepth,
      int supportSampleGridSize,
      double supportThreshold,
      double surfaceSkySupportThreshold,
      double smallSkySupportThreshold,
      double surfaceSkyFootprintInsetRatio,
      double smallSkyFootprintInsetRatio,
      int surfaceSkySearchRadiusChunks,
      int smallSkySearchRadiusChunks,
      int surfaceSkyMinStableTopCells,
      int smallSkyMinStableTopCells,
      int surfaceSkyTopOffset,
      int smallSkyTopOffset,
      int surfaceSkyLocalSearchStepBlocks,
      int smallSkyLocalSearchStepBlocks,
      int surfaceSkyLocalSearchRadiusBlocks,
      int smallSkyLocalSearchRadiusBlocks,
      double surfaceSkyGroundedSampleThreshold,
      double smallSkyGroundedSampleThreshold,
      int surfaceSkyMaxGroundGapBlocks,
      int smallSkyMaxGroundGapBlocks,
      int surfaceSkyMinHostIslandRadius,
      int smallSkyMinHostIslandRadius,
      int surfaceSkyMinHostStableTopCells,
      int smallSkyMinHostStableTopCells,
      boolean defaultNearMissFallbackEnabled,
      List<String> structureWhitelistEntries,
      List<String> structureDenylistEntries,
      List<String> structureCategoryOverrideEntries
   ) {
      return generator(
         islandDensity,
         minIslandRadius,
         maxIslandRadius,
         islandSizeMode,
         smallIslandSizeBand,
         mediumIslandSizeBand,
         largeIslandSizeBand,
         minIslandY,
         maxIslandY,
         140,
         lowBandWeight,
         midHighBandWeight,
         veryHighBandWeight,
         lowBandCenterOffset,
         veryHighBandCenterOffset,
         ClusterSpacingMode.CONSISTENT,
         clusterSpacing,
         clusterSpacing,
         clusterSpacing,
         terrainReliefScale,
         classicArchetypeEnabled,
         classicArchetypeWeight,
         bowlCraterArchetypeEnabled,
         bowlCraterArchetypeWeight,
         crescentArchetypeEnabled,
         crescentArchetypeWeight,
         terraceArchetypeEnabled,
         terraceArchetypeWeight,
         oceanEnabled,
         oceanLevelY,
         false,
         18,
         10,
         0.05,
         8,
         40,
         oceanBlockType,
         supportCheckDepth,
         supportSampleGridSize,
         supportThreshold,
         surfaceSkySupportThreshold,
         smallSkySupportThreshold,
         surfaceSkyFootprintInsetRatio,
         smallSkyFootprintInsetRatio,
         surfaceSkySearchRadiusChunks,
         smallSkySearchRadiusChunks,
         surfaceSkyMinStableTopCells,
         smallSkyMinStableTopCells,
         surfaceSkyTopOffset,
         smallSkyTopOffset,
         smallSkyLocalSearchStepBlocks,
         smallSkyLocalSearchStepBlocks,
         surfaceSkyLocalSearchRadiusBlocks,
         smallSkyLocalSearchRadiusBlocks,
         surfaceSkyGroundedSampleThreshold,
         smallSkyGroundedSampleThreshold,
         surfaceSkyMaxGroundGapBlocks,
         smallSkyMaxGroundGapBlocks,
         surfaceSkyMinHostIslandRadius,
         smallSkyMinHostIslandRadius,
         surfaceSkyMinHostStableTopCells,
         smallSkyMinHostStableTopCells,
         defaultNearMissFallbackEnabled,
         true,
         true,
         true,
         false,
         16,
         true,
         4,
         8,
         true,
         TerrainOverlapMode.VOID,
         structureWhitelistEntries,
         structureDenylistEntries,
         structureCategoryOverrideEntries,
         SkyIslandSettingLimits.DEFAULT_WATER_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_SKY_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_GROUND_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_UNDERGROUND_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_VILLAGE_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_STRONGHOLD_STRUCTURE_CATEGORY_TOKENS
      );
   }

   public static SkyIslandGeneratorSettings generator(
      double islandDensity,
      int minIslandRadius,
      int maxIslandRadius,
      IslandSizeMode islandSizeMode,
      IslandSizeBand smallIslandSizeBand,
      IslandSizeBand mediumIslandSizeBand,
      IslandSizeBand largeIslandSizeBand,
      int minIslandY,
      int maxIslandY,
      int maxIslandThicknessBlocks,
      double lowBandWeight,
      double midHighBandWeight,
      double veryHighBandWeight,
      int lowBandCenterOffset,
      int veryHighBandCenterOffset,
      int clusterSpacing,
      double terrainReliefScale,
      boolean classicArchetypeEnabled,
      double classicArchetypeWeight,
      boolean bowlCraterArchetypeEnabled,
      double bowlCraterArchetypeWeight,
      boolean crescentArchetypeEnabled,
      double crescentArchetypeWeight,
      boolean terraceArchetypeEnabled,
      double terraceArchetypeWeight,
      boolean oceanEnabled,
      int oceanLevelY,
      OceanBlockType oceanBlockType,
      int supportCheckDepth,
      int supportSampleGridSize,
      double supportThreshold,
      double surfaceSkySupportThreshold,
      double smallSkySupportThreshold,
      double surfaceSkyFootprintInsetRatio,
      double smallSkyFootprintInsetRatio,
      int surfaceSkySearchRadiusChunks,
      int smallSkySearchRadiusChunks,
      int surfaceSkyMinStableTopCells,
      int smallSkyMinStableTopCells,
      int surfaceSkyTopOffset,
      int smallSkyTopOffset,
      int surfaceSkyLocalSearchStepBlocks,
      int smallSkyLocalSearchStepBlocks,
      int surfaceSkyLocalSearchRadiusBlocks,
      int smallSkyLocalSearchRadiusBlocks,
      double surfaceSkyGroundedSampleThreshold,
      double smallSkyGroundedSampleThreshold,
      int surfaceSkyMaxGroundGapBlocks,
      int smallSkyMaxGroundGapBlocks,
      int surfaceSkyMinHostIslandRadius,
      int smallSkyMinHostIslandRadius,
      int surfaceSkyMinHostStableTopCells,
      int smallSkyMinHostStableTopCells,
      boolean defaultNearMissFallbackEnabled,
      List<String> structureWhitelistEntries,
      List<String> structureDenylistEntries,
      List<String> structureCategoryOverrideEntries
   ) {
      return generator(
         islandDensity,
         minIslandRadius,
         maxIslandRadius,
         islandSizeMode,
         smallIslandSizeBand,
         mediumIslandSizeBand,
         largeIslandSizeBand,
         minIslandY,
         maxIslandY,
         maxIslandThicknessBlocks,
         lowBandWeight,
         midHighBandWeight,
         veryHighBandWeight,
         lowBandCenterOffset,
         veryHighBandCenterOffset,
         ClusterSpacingMode.CONSISTENT,
         clusterSpacing,
         clusterSpacing,
         clusterSpacing,
         terrainReliefScale,
         classicArchetypeEnabled,
         classicArchetypeWeight,
         bowlCraterArchetypeEnabled,
         bowlCraterArchetypeWeight,
         crescentArchetypeEnabled,
         crescentArchetypeWeight,
         terraceArchetypeEnabled,
         terraceArchetypeWeight,
         oceanEnabled,
         oceanLevelY,
         false,
         18,
         10,
         0.05,
         8,
         40,
         oceanBlockType,
         supportCheckDepth,
         supportSampleGridSize,
         supportThreshold,
         surfaceSkySupportThreshold,
         smallSkySupportThreshold,
         surfaceSkyFootprintInsetRatio,
         smallSkyFootprintInsetRatio,
         surfaceSkySearchRadiusChunks,
         smallSkySearchRadiusChunks,
         surfaceSkyMinStableTopCells,
         smallSkyMinStableTopCells,
         surfaceSkyTopOffset,
         smallSkyTopOffset,
         surfaceSkyLocalSearchStepBlocks,
         surfaceSkyLocalSearchStepBlocks,
         surfaceSkyLocalSearchRadiusBlocks,
         smallSkyLocalSearchRadiusBlocks,
         surfaceSkyGroundedSampleThreshold,
         smallSkyGroundedSampleThreshold,
         surfaceSkyMaxGroundGapBlocks,
         smallSkyMaxGroundGapBlocks,
         surfaceSkyMinHostIslandRadius,
         smallSkyMinHostIslandRadius,
         surfaceSkyMinHostStableTopCells,
         smallSkyMinHostStableTopCells,
         defaultNearMissFallbackEnabled,
         true,
         true,
         true,
         false,
         16,
         true,
         4,
         8,
         true,
         TerrainOverlapMode.VOID,
         structureWhitelistEntries,
         structureDenylistEntries,
         structureCategoryOverrideEntries,
         SkyIslandSettingLimits.DEFAULT_WATER_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_SKY_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_GROUND_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_UNDERGROUND_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_VILLAGE_STRUCTURE_CATEGORY_TOKENS,
         SkyIslandSettingLimits.DEFAULT_STRONGHOLD_STRUCTURE_CATEGORY_TOKENS
      );
   }

   public static SkyIslandGeneratorSettings generator(
      double islandDensity,
      int minIslandRadius,
      int maxIslandRadius,
      IslandSizeMode islandSizeMode,
      IslandSizeBand smallIslandSizeBand,
      IslandSizeBand mediumIslandSizeBand,
      IslandSizeBand largeIslandSizeBand,
      int minIslandY,
      int maxIslandY,
      int maxIslandThicknessBlocks,
      double lowBandWeight,
      double midHighBandWeight,
      double veryHighBandWeight,
      int lowBandCenterOffset,
      int veryHighBandCenterOffset,
      ClusterSpacingMode clusterSpacingMode,
      int clusterSpacing,
      int minClusterSpacing,
      int maxClusterSpacing,
      double terrainReliefScale,
      boolean classicArchetypeEnabled,
      double classicArchetypeWeight,
      boolean bowlCraterArchetypeEnabled,
      double bowlCraterArchetypeWeight,
      boolean crescentArchetypeEnabled,
      double crescentArchetypeWeight,
      boolean terraceArchetypeEnabled,
      double terraceArchetypeWeight,
      boolean oceanEnabled,
      int oceanLevelY,
      boolean oceanFloorNoiseEnabled,
      int oceanFloorBaseOffset,
      int oceanFloorNoiseAmplitude,
      double oceanFloorNoiseScale,
      int oceanFloorMinDepth,
      int oceanFloorMaxDepth,
      OceanBlockType oceanBlockType,
      int supportCheckDepth,
      int supportSampleGridSize,
      double supportThreshold,
      double surfaceSkySupportThreshold,
      double smallSkySupportThreshold,
      double surfaceSkyFootprintInsetRatio,
      double smallSkyFootprintInsetRatio,
      int surfaceSkySearchRadiusChunks,
      int smallSkySearchRadiusChunks,
      int surfaceSkyMinStableTopCells,
      int smallSkyMinStableTopCells,
      int surfaceSkyTopOffset,
      int smallSkyTopOffset,
      int surfaceSkyLocalSearchStepBlocks,
      int smallSkyLocalSearchStepBlocks,
      int surfaceSkyLocalSearchRadiusBlocks,
      int smallSkyLocalSearchRadiusBlocks,
      double surfaceSkyGroundedSampleThreshold,
      double smallSkyGroundedSampleThreshold,
      int surfaceSkyMaxGroundGapBlocks,
      int smallSkyMaxGroundGapBlocks,
      int surfaceSkyMinHostIslandRadius,
      int smallSkyMinHostIslandRadius,
      int surfaceSkyMinHostStableTopCells,
      int smallSkyMinHostStableTopCells,
      boolean defaultNearMissFallbackEnabled,
      boolean customStructureRulesEnabled,
      boolean clusterCompanionIslandsEnabled,
      boolean anchorFragmentationEnabled,
      boolean disableIslandsOverOceanBiomes,
      int deepslateStartY,
      boolean biomeProfileBlendingEnabled,
      int biomeProfileBlendingRadiusBlocks,
      int biomeProfileBlendingQuantizationSteps,
      boolean biomeProfileBlendingBoundaryOnly,
      TerrainOverlapMode terrainOverlapMode,
      List<String> structureWhitelistEntries,
      List<String> structureDenylistEntries,
      List<String> structureCategoryOverrideEntries,
      List<String> waterStructureCategoryTokens,
      List<String> skyStructureCategoryTokens,
      List<String> groundStructureCategoryTokens,
      List<String> undergroundStructureCategoryTokens,
      List<String> villageStructureCategoryTokens,
      List<String> strongholdStructureCategoryTokens
   ) {
      return new SkyIslandGeneratorSettings(
         terrain(
            islandDensity,
            minIslandRadius,
            maxIslandRadius,
            islandSizeMode,
            smallIslandSizeBand,
            mediumIslandSizeBand,
            largeIslandSizeBand,
            minIslandY,
            maxIslandY,
            maxIslandThicknessBlocks,
            lowBandWeight,
            midHighBandWeight,
            veryHighBandWeight,
            lowBandCenterOffset,
            veryHighBandCenterOffset,
            clusterSpacingMode,
            clusterSpacing,
            minClusterSpacing,
            maxClusterSpacing,
            terrainReliefScale,
            classicArchetypeEnabled,
            classicArchetypeWeight,
            bowlCraterArchetypeEnabled,
            bowlCraterArchetypeWeight,
            crescentArchetypeEnabled,
            crescentArchetypeWeight,
            terraceArchetypeEnabled,
            terraceArchetypeWeight,
            oceanEnabled,
            oceanLevelY,
            oceanFloorNoiseEnabled,
            oceanFloorBaseOffset,
            oceanFloorNoiseAmplitude,
            oceanFloorNoiseScale,
            oceanFloorMinDepth,
            oceanFloorMaxDepth
         ),
         new StructureSupportSettings(supportCheckDepth, supportSampleGridSize, supportThreshold),
         category(
            surfaceSkySupportThreshold,
            surfaceSkyFootprintInsetRatio,
            surfaceSkySearchRadiusChunks,
            surfaceSkyMinStableTopCells,
            surfaceSkyTopOffset,
            surfaceSkyLocalSearchStepBlocks,
            surfaceSkyLocalSearchRadiusBlocks,
            surfaceSkyGroundedSampleThreshold,
            surfaceSkyMaxGroundGapBlocks,
            surfaceSkyMinHostIslandRadius,
            surfaceSkyMinHostStableTopCells
         ),
         category(
            smallSkySupportThreshold,
            smallSkyFootprintInsetRatio,
            smallSkySearchRadiusChunks,
            smallSkyMinStableTopCells,
            smallSkyTopOffset,
            smallSkyLocalSearchStepBlocks,
            smallSkyLocalSearchRadiusBlocks,
            smallSkyGroundedSampleThreshold,
            smallSkyMaxGroundGapBlocks,
            smallSkyMinHostIslandRadius,
            smallSkyMinHostStableTopCells
         ),
         new AdvancedGeneratorSettings(
            defaultNearMissFallbackEnabled,
            customStructureRulesEnabled,
            clusterCompanionIslandsEnabled,
            anchorFragmentationEnabled,
            disableIslandsOverOceanBiomes,
            deepslateStartY,
            biomeProfileBlendingEnabled,
            biomeProfileBlendingRadiusBlocks,
            biomeProfileBlendingQuantizationSteps,
            biomeProfileBlendingBoundaryOnly,
            terrainOverlapMode,
            oceanBlockType,
            structureWhitelistEntries,
            structureDenylistEntries,
            structureCategoryOverrideEntries,
            waterStructureCategoryTokens,
            skyStructureCategoryTokens,
            groundStructureCategoryTokens,
            undergroundStructureCategoryTokens,
            villageStructureCategoryTokens,
            strongholdStructureCategoryTokens
         )
      );
   }

   public static SkyIslandSettings runtime(
      double islandDensity,
      int minIslandRadius,
      int maxIslandRadius,
      IslandSizeMode islandSizeMode,
      IslandSizeBand smallIslandSizeBand,
      IslandSizeBand mediumIslandSizeBand,
      IslandSizeBand largeIslandSizeBand,
      int minIslandY,
      int maxIslandY,
      double lowBandWeight,
      double midHighBandWeight,
      double veryHighBandWeight,
      int lowBandCenterOffset,
      int veryHighBandCenterOffset,
      int clusterSpacing,
      double terrainReliefScale,
      boolean classicArchetypeEnabled,
      double classicArchetypeWeight,
      boolean bowlCraterArchetypeEnabled,
      double bowlCraterArchetypeWeight,
      boolean crescentArchetypeEnabled,
      double crescentArchetypeWeight,
      boolean terraceArchetypeEnabled,
      double terraceArchetypeWeight,
      boolean oceanEnabled,
      int oceanLevelY,
      OceanBlockType oceanBlockType,
      int supportCheckDepth,
      int supportSampleGridSize,
      double supportThreshold,
      double surfaceSkySupportThreshold,
      double smallSkySupportThreshold,
      double surfaceSkyFootprintInsetRatio,
      double smallSkyFootprintInsetRatio,
      int surfaceSkySearchRadiusChunks,
      int smallSkySearchRadiusChunks,
      int surfaceSkyMinStableTopCells,
      int smallSkyMinStableTopCells,
      int surfaceSkyTopOffset,
      int smallSkyTopOffset,
      int surfaceSkyLocalSearchStepBlocks,
      int smallSkyLocalSearchStepBlocks,
      int surfaceSkyLocalSearchRadiusBlocks,
      int smallSkyLocalSearchRadiusBlocks,
      double surfaceSkyGroundedSampleThreshold,
      double smallSkyGroundedSampleThreshold,
      int surfaceSkyMaxGroundGapBlocks,
      int smallSkyMaxGroundGapBlocks,
      int surfaceSkyMinHostIslandRadius,
      int smallSkyMinHostIslandRadius,
      int surfaceSkyMinHostStableTopCells,
      int smallSkyMinHostStableTopCells,
      boolean defaultNearMissFallbackEnabled,
      StructureWhitelist structureWhitelist,
      StructurePlacementPolicy structurePlacementPolicy
   ) {
      return runtime(
         islandDensity,
         minIslandRadius,
         maxIslandRadius,
         islandSizeMode,
         smallIslandSizeBand,
         mediumIslandSizeBand,
         largeIslandSizeBand,
         minIslandY,
         maxIslandY,
         140,
         lowBandWeight,
         midHighBandWeight,
         veryHighBandWeight,
         lowBandCenterOffset,
         veryHighBandCenterOffset,
         ClusterSpacingMode.CONSISTENT,
         clusterSpacing,
         clusterSpacing,
         clusterSpacing,
         terrainReliefScale,
         classicArchetypeEnabled,
         classicArchetypeWeight,
         bowlCraterArchetypeEnabled,
         bowlCraterArchetypeWeight,
         crescentArchetypeEnabled,
         crescentArchetypeWeight,
         terraceArchetypeEnabled,
         terraceArchetypeWeight,
         oceanEnabled,
         oceanLevelY,
         false,
         18,
         10,
         0.05,
         8,
         40,
         oceanBlockType,
         supportCheckDepth,
         supportSampleGridSize,
         supportThreshold,
         surfaceSkySupportThreshold,
         smallSkySupportThreshold,
         surfaceSkyFootprintInsetRatio,
         smallSkyFootprintInsetRatio,
         surfaceSkySearchRadiusChunks,
         smallSkySearchRadiusChunks,
         surfaceSkyMinStableTopCells,
         smallSkyMinStableTopCells,
         surfaceSkyTopOffset,
         smallSkyTopOffset,
         surfaceSkyLocalSearchStepBlocks,
         smallSkyLocalSearchStepBlocks,
         surfaceSkyLocalSearchRadiusBlocks,
         smallSkyLocalSearchRadiusBlocks,
         surfaceSkyGroundedSampleThreshold,
         smallSkyGroundedSampleThreshold,
         surfaceSkyMaxGroundGapBlocks,
         smallSkyMaxGroundGapBlocks,
         surfaceSkyMinHostIslandRadius,
         smallSkyMinHostIslandRadius,
         surfaceSkyMinHostStableTopCells,
         smallSkyMinHostStableTopCells,
         defaultNearMissFallbackEnabled,
         true,
         true,
         true,
         false,
         16,
         true,
         4,
         8,
         true,
         TerrainOverlapMode.VOID,
         structureWhitelist,
         structurePlacementPolicy
      );
   }

   public static SkyIslandSettings runtime(
      double islandDensity,
      int minIslandRadius,
      int maxIslandRadius,
      IslandSizeMode islandSizeMode,
      IslandSizeBand smallIslandSizeBand,
      IslandSizeBand mediumIslandSizeBand,
      IslandSizeBand largeIslandSizeBand,
      int minIslandY,
      int maxIslandY,
      double lowBandWeight,
      double midHighBandWeight,
      double veryHighBandWeight,
      int lowBandCenterOffset,
      int veryHighBandCenterOffset,
      ClusterSpacingMode clusterSpacingMode,
      int clusterSpacing,
      int minClusterSpacing,
      int maxClusterSpacing,
      double terrainReliefScale,
      boolean classicArchetypeEnabled,
      double classicArchetypeWeight,
      boolean bowlCraterArchetypeEnabled,
      double bowlCraterArchetypeWeight,
      boolean crescentArchetypeEnabled,
      double crescentArchetypeWeight,
      boolean terraceArchetypeEnabled,
      double terraceArchetypeWeight,
      boolean oceanEnabled,
      int oceanLevelY,
      boolean oceanFloorNoiseEnabled,
      int oceanFloorBaseOffset,
      int oceanFloorNoiseAmplitude,
      double oceanFloorNoiseScale,
      int oceanFloorMinDepth,
      int oceanFloorMaxDepth,
      OceanBlockType oceanBlockType,
      int supportCheckDepth,
      int supportSampleGridSize,
      double supportThreshold,
      double surfaceSkySupportThreshold,
      double smallSkySupportThreshold,
      double surfaceSkyFootprintInsetRatio,
      double smallSkyFootprintInsetRatio,
      int surfaceSkySearchRadiusChunks,
      int smallSkySearchRadiusChunks,
      int surfaceSkyMinStableTopCells,
      int smallSkyMinStableTopCells,
      int surfaceSkyTopOffset,
      int smallSkyTopOffset,
      int surfaceSkyLocalSearchStepBlocks,
      int smallSkyLocalSearchStepBlocks,
      int surfaceSkyLocalSearchRadiusBlocks,
      int smallSkyLocalSearchRadiusBlocks,
      double surfaceSkyGroundedSampleThreshold,
      double smallSkyGroundedSampleThreshold,
      int surfaceSkyMaxGroundGapBlocks,
      int smallSkyMaxGroundGapBlocks,
      int surfaceSkyMinHostIslandRadius,
      int smallSkyMinHostIslandRadius,
      int surfaceSkyMinHostStableTopCells,
      int smallSkyMinHostStableTopCells,
      boolean defaultNearMissFallbackEnabled,
      boolean customStructureRulesEnabled,
      boolean clusterCompanionIslandsEnabled,
      boolean anchorFragmentationEnabled,
      boolean disableIslandsOverOceanBiomes,
      int deepslateStartY,
      boolean biomeProfileBlendingEnabled,
      int biomeProfileBlendingRadiusBlocks,
      int biomeProfileBlendingQuantizationSteps,
      boolean biomeProfileBlendingBoundaryOnly,
      StructureWhitelist structureWhitelist,
      StructurePlacementPolicy structurePlacementPolicy
   ) {
      return runtime(
         islandDensity,
         minIslandRadius,
         maxIslandRadius,
         islandSizeMode,
         smallIslandSizeBand,
         mediumIslandSizeBand,
         largeIslandSizeBand,
         minIslandY,
         maxIslandY,
         140,
         lowBandWeight,
         midHighBandWeight,
         veryHighBandWeight,
         lowBandCenterOffset,
         veryHighBandCenterOffset,
         clusterSpacingMode,
         clusterSpacing,
         minClusterSpacing,
         maxClusterSpacing,
         terrainReliefScale,
         classicArchetypeEnabled,
         classicArchetypeWeight,
         bowlCraterArchetypeEnabled,
         bowlCraterArchetypeWeight,
         crescentArchetypeEnabled,
         crescentArchetypeWeight,
         terraceArchetypeEnabled,
         terraceArchetypeWeight,
         oceanEnabled,
         oceanLevelY,
         oceanFloorNoiseEnabled,
         oceanFloorBaseOffset,
         oceanFloorNoiseAmplitude,
         oceanFloorNoiseScale,
         oceanFloorMinDepth,
         oceanFloorMaxDepth,
         oceanBlockType,
         supportCheckDepth,
         supportSampleGridSize,
         supportThreshold,
         surfaceSkySupportThreshold,
         smallSkySupportThreshold,
         surfaceSkyFootprintInsetRatio,
         smallSkyFootprintInsetRatio,
         surfaceSkySearchRadiusChunks,
         smallSkySearchRadiusChunks,
         surfaceSkyMinStableTopCells,
         smallSkyMinStableTopCells,
         surfaceSkyTopOffset,
         smallSkyTopOffset,
         surfaceSkyLocalSearchStepBlocks,
         smallSkyLocalSearchStepBlocks,
         surfaceSkyLocalSearchRadiusBlocks,
         smallSkyLocalSearchRadiusBlocks,
         surfaceSkyGroundedSampleThreshold,
         smallSkyGroundedSampleThreshold,
         surfaceSkyMaxGroundGapBlocks,
         smallSkyMaxGroundGapBlocks,
         surfaceSkyMinHostIslandRadius,
         smallSkyMinHostIslandRadius,
         surfaceSkyMinHostStableTopCells,
         smallSkyMinHostStableTopCells,
         defaultNearMissFallbackEnabled,
         customStructureRulesEnabled,
         clusterCompanionIslandsEnabled,
         anchorFragmentationEnabled,
         disableIslandsOverOceanBiomes,
         deepslateStartY,
         biomeProfileBlendingEnabled,
         biomeProfileBlendingRadiusBlocks,
         biomeProfileBlendingQuantizationSteps,
         biomeProfileBlendingBoundaryOnly,
         TerrainOverlapMode.VOID,
         structureWhitelist,
         structurePlacementPolicy
      );
   }

   public static SkyIslandSettings runtime(
      double islandDensity,
      int minIslandRadius,
      int maxIslandRadius,
      IslandSizeMode islandSizeMode,
      IslandSizeBand smallIslandSizeBand,
      IslandSizeBand mediumIslandSizeBand,
      IslandSizeBand largeIslandSizeBand,
      int minIslandY,
      int maxIslandY,
      double lowBandWeight,
      double midHighBandWeight,
      double veryHighBandWeight,
      int lowBandCenterOffset,
      int veryHighBandCenterOffset,
      int clusterSpacing,
      double terrainReliefScale,
      boolean classicArchetypeEnabled,
      double classicArchetypeWeight,
      boolean bowlCraterArchetypeEnabled,
      double bowlCraterArchetypeWeight,
      boolean crescentArchetypeEnabled,
      double crescentArchetypeWeight,
      boolean terraceArchetypeEnabled,
      double terraceArchetypeWeight,
      boolean oceanEnabled,
      int oceanLevelY,
      boolean oceanFloorNoiseEnabled,
      int oceanFloorBaseOffset,
      int oceanFloorNoiseAmplitude,
      double oceanFloorNoiseScale,
      int oceanFloorMinDepth,
      int oceanFloorMaxDepth,
      OceanBlockType oceanBlockType,
      int supportCheckDepth,
      int supportSampleGridSize,
      double supportThreshold,
      double surfaceSkySupportThreshold,
      double smallSkySupportThreshold,
      double surfaceSkyFootprintInsetRatio,
      double smallSkyFootprintInsetRatio,
      int surfaceSkySearchRadiusChunks,
      int smallSkySearchRadiusChunks,
      int surfaceSkyMinStableTopCells,
      int smallSkyMinStableTopCells,
      int surfaceSkyTopOffset,
      int smallSkyTopOffset,
      int surfaceSkyLocalSearchStepBlocks,
      int smallSkyLocalSearchStepBlocks,
      int surfaceSkyLocalSearchRadiusBlocks,
      int smallSkyLocalSearchRadiusBlocks,
      double surfaceSkyGroundedSampleThreshold,
      double smallSkyGroundedSampleThreshold,
      int surfaceSkyMaxGroundGapBlocks,
      int smallSkyMaxGroundGapBlocks,
      int surfaceSkyMinHostIslandRadius,
      int smallSkyMinHostIslandRadius,
      int surfaceSkyMinHostStableTopCells,
      int smallSkyMinHostStableTopCells,
      boolean defaultNearMissFallbackEnabled,
      StructureWhitelist structureWhitelist,
      StructurePlacementPolicy structurePlacementPolicy
   ) {
      return runtime(
         islandDensity,
         minIslandRadius,
         maxIslandRadius,
         islandSizeMode,
         smallIslandSizeBand,
         mediumIslandSizeBand,
         largeIslandSizeBand,
         minIslandY,
         maxIslandY,
         140,
         lowBandWeight,
         midHighBandWeight,
         veryHighBandWeight,
         lowBandCenterOffset,
         veryHighBandCenterOffset,
         ClusterSpacingMode.CONSISTENT,
         clusterSpacing,
         clusterSpacing,
         clusterSpacing,
         terrainReliefScale,
         classicArchetypeEnabled,
         classicArchetypeWeight,
         bowlCraterArchetypeEnabled,
         bowlCraterArchetypeWeight,
         crescentArchetypeEnabled,
         crescentArchetypeWeight,
         terraceArchetypeEnabled,
         terraceArchetypeWeight,
         oceanEnabled,
         oceanLevelY,
         oceanFloorNoiseEnabled,
         oceanFloorBaseOffset,
         oceanFloorNoiseAmplitude,
         oceanFloorNoiseScale,
         oceanFloorMinDepth,
         oceanFloorMaxDepth,
         oceanBlockType,
         supportCheckDepth,
         supportSampleGridSize,
         supportThreshold,
         surfaceSkySupportThreshold,
         smallSkySupportThreshold,
         surfaceSkyFootprintInsetRatio,
         smallSkyFootprintInsetRatio,
         surfaceSkySearchRadiusChunks,
         smallSkySearchRadiusChunks,
         surfaceSkyMinStableTopCells,
         smallSkyMinStableTopCells,
         surfaceSkyTopOffset,
         smallSkyTopOffset,
         surfaceSkyLocalSearchStepBlocks,
         smallSkyLocalSearchStepBlocks,
         surfaceSkyLocalSearchRadiusBlocks,
         smallSkyLocalSearchRadiusBlocks,
         surfaceSkyGroundedSampleThreshold,
         smallSkyGroundedSampleThreshold,
         surfaceSkyMaxGroundGapBlocks,
         smallSkyMaxGroundGapBlocks,
         surfaceSkyMinHostIslandRadius,
         smallSkyMinHostIslandRadius,
         surfaceSkyMinHostStableTopCells,
         smallSkyMinHostStableTopCells,
         defaultNearMissFallbackEnabled,
         true,
         true,
         true,
         false,
         16,
         true,
         4,
         8,
         true,
         TerrainOverlapMode.VOID,
         structureWhitelist,
         structurePlacementPolicy
      );
   }

   public static SkyIslandSettings runtime(
      double islandDensity,
      int minIslandRadius,
      int maxIslandRadius,
      IslandSizeMode islandSizeMode,
      IslandSizeBand smallIslandSizeBand,
      IslandSizeBand mediumIslandSizeBand,
      IslandSizeBand largeIslandSizeBand,
      int minIslandY,
      int maxIslandY,
      int maxIslandThicknessBlocks,
      double lowBandWeight,
      double midHighBandWeight,
      double veryHighBandWeight,
      int lowBandCenterOffset,
      int veryHighBandCenterOffset,
      ClusterSpacingMode clusterSpacingMode,
      int clusterSpacing,
      int minClusterSpacing,
      int maxClusterSpacing,
      double terrainReliefScale,
      boolean classicArchetypeEnabled,
      double classicArchetypeWeight,
      boolean bowlCraterArchetypeEnabled,
      double bowlCraterArchetypeWeight,
      boolean crescentArchetypeEnabled,
      double crescentArchetypeWeight,
      boolean terraceArchetypeEnabled,
      double terraceArchetypeWeight,
      boolean oceanEnabled,
      int oceanLevelY,
      boolean oceanFloorNoiseEnabled,
      int oceanFloorBaseOffset,
      int oceanFloorNoiseAmplitude,
      double oceanFloorNoiseScale,
      int oceanFloorMinDepth,
      int oceanFloorMaxDepth,
      OceanBlockType oceanBlockType,
      int supportCheckDepth,
      int supportSampleGridSize,
      double supportThreshold,
      double surfaceSkySupportThreshold,
      double smallSkySupportThreshold,
      double surfaceSkyFootprintInsetRatio,
      double smallSkyFootprintInsetRatio,
      int surfaceSkySearchRadiusChunks,
      int smallSkySearchRadiusChunks,
      int surfaceSkyMinStableTopCells,
      int smallSkyMinStableTopCells,
      int surfaceSkyTopOffset,
      int smallSkyTopOffset,
      int surfaceSkyLocalSearchStepBlocks,
      int smallSkyLocalSearchStepBlocks,
      int surfaceSkyLocalSearchRadiusBlocks,
      int smallSkyLocalSearchRadiusBlocks,
      double surfaceSkyGroundedSampleThreshold,
      double smallSkyGroundedSampleThreshold,
      int surfaceSkyMaxGroundGapBlocks,
      int smallSkyMaxGroundGapBlocks,
      int surfaceSkyMinHostIslandRadius,
      int smallSkyMinHostIslandRadius,
      int surfaceSkyMinHostStableTopCells,
      int smallSkyMinHostStableTopCells,
      boolean defaultNearMissFallbackEnabled,
      boolean customStructureRulesEnabled,
      boolean clusterCompanionIslandsEnabled,
      boolean anchorFragmentationEnabled,
      boolean disableIslandsOverOceanBiomes,
      int deepslateStartY,
      boolean biomeProfileBlendingEnabled,
      int biomeProfileBlendingRadiusBlocks,
      int biomeProfileBlendingQuantizationSteps,
      boolean biomeProfileBlendingBoundaryOnly,
      TerrainOverlapMode terrainOverlapMode,
      StructureWhitelist structureWhitelist,
      StructurePlacementPolicy structurePlacementPolicy
   ) {
      return new SkyIslandSettings(
         terrain(
            islandDensity,
            minIslandRadius,
            maxIslandRadius,
            islandSizeMode,
            smallIslandSizeBand,
            mediumIslandSizeBand,
            largeIslandSizeBand,
            minIslandY,
            maxIslandY,
            maxIslandThicknessBlocks,
            lowBandWeight,
            midHighBandWeight,
            veryHighBandWeight,
            lowBandCenterOffset,
            veryHighBandCenterOffset,
            clusterSpacingMode,
            clusterSpacing,
            minClusterSpacing,
            maxClusterSpacing,
            terrainReliefScale,
            classicArchetypeEnabled,
            classicArchetypeWeight,
            bowlCraterArchetypeEnabled,
            bowlCraterArchetypeWeight,
            crescentArchetypeEnabled,
            crescentArchetypeWeight,
            terraceArchetypeEnabled,
            terraceArchetypeWeight,
            oceanEnabled,
            oceanLevelY,
            oceanFloorNoiseEnabled,
            oceanFloorBaseOffset,
            oceanFloorNoiseAmplitude,
            oceanFloorNoiseScale,
            oceanFloorMinDepth,
            oceanFloorMaxDepth
         ),
         new StructureSupportSettings(supportCheckDepth, supportSampleGridSize, supportThreshold),
         category(
            surfaceSkySupportThreshold,
            surfaceSkyFootprintInsetRatio,
            surfaceSkySearchRadiusChunks,
            surfaceSkyMinStableTopCells,
            surfaceSkyTopOffset,
            surfaceSkyLocalSearchStepBlocks,
            surfaceSkyLocalSearchRadiusBlocks,
            surfaceSkyGroundedSampleThreshold,
            surfaceSkyMaxGroundGapBlocks,
            surfaceSkyMinHostIslandRadius,
            surfaceSkyMinHostStableTopCells
         ),
         category(
            smallSkySupportThreshold,
            smallSkyFootprintInsetRatio,
            smallSkySearchRadiusChunks,
            smallSkyMinStableTopCells,
            smallSkyTopOffset,
            smallSkyLocalSearchStepBlocks,
            smallSkyLocalSearchRadiusBlocks,
            smallSkyGroundedSampleThreshold,
            smallSkyMaxGroundGapBlocks,
            smallSkyMinHostIslandRadius,
            smallSkyMinHostStableTopCells
         ),
         new AdvancedRuntimeSettings(
            defaultNearMissFallbackEnabled,
            customStructureRulesEnabled,
            clusterCompanionIslandsEnabled,
            anchorFragmentationEnabled,
            disableIslandsOverOceanBiomes,
            deepslateStartY,
            biomeProfileBlendingEnabled,
            biomeProfileBlendingRadiusBlocks,
            biomeProfileBlendingQuantizationSteps,
            biomeProfileBlendingBoundaryOnly,
            terrainOverlapMode,
            oceanBlockType,
            structureWhitelist,
            structurePlacementPolicy
         )
      );
   }

   private static TerrainSettings terrain(
      double islandDensity,
      int minIslandRadius,
      int maxIslandRadius,
      IslandSizeMode islandSizeMode,
      IslandSizeBand smallIslandSizeBand,
      IslandSizeBand mediumIslandSizeBand,
      IslandSizeBand largeIslandSizeBand,
      int minIslandY,
      int maxIslandY,
      int maxIslandThicknessBlocks,
      double lowBandWeight,
      double midHighBandWeight,
      double veryHighBandWeight,
      int lowBandCenterOffset,
      int veryHighBandCenterOffset,
      ClusterSpacingMode clusterSpacingMode,
      int clusterSpacing,
      int minClusterSpacing,
      int maxClusterSpacing,
      double terrainReliefScale,
      boolean classicArchetypeEnabled,
      double classicArchetypeWeight,
      boolean bowlCraterArchetypeEnabled,
      double bowlCraterArchetypeWeight,
      boolean crescentArchetypeEnabled,
      double crescentArchetypeWeight,
      boolean terraceArchetypeEnabled,
      double terraceArchetypeWeight,
      boolean oceanEnabled,
      int oceanLevelY,
      boolean oceanFloorNoiseEnabled,
      int oceanFloorBaseOffset,
      int oceanFloorNoiseAmplitude,
      double oceanFloorNoiseScale,
      int oceanFloorMinDepth,
      int oceanFloorMaxDepth
   ) {
      return new TerrainSettings(
         islandDensity,
         minIslandRadius,
         maxIslandRadius,
         new IslandSizeSettings(islandSizeMode, smallIslandSizeBand, mediumIslandSizeBand, largeIslandSizeBand),
         minIslandY,
         maxIslandY,
         maxIslandThicknessBlocks,
         lowBandWeight,
         midHighBandWeight,
         veryHighBandWeight,
         lowBandCenterOffset,
         veryHighBandCenterOffset,
         new ClusterSpacingSettings(clusterSpacingMode, clusterSpacing, minClusterSpacing, maxClusterSpacing),
         terrainReliefScale,
         new ArchetypeSettings(
            classicArchetypeEnabled,
            classicArchetypeWeight,
            bowlCraterArchetypeEnabled,
            bowlCraterArchetypeWeight,
            crescentArchetypeEnabled,
            crescentArchetypeWeight,
            terraceArchetypeEnabled,
            terraceArchetypeWeight
         ),
         new OceanSettings(
            oceanEnabled,
            oceanLevelY,
            oceanFloorNoiseEnabled,
            oceanFloorBaseOffset,
            oceanFloorNoiseAmplitude,
            oceanFloorNoiseScale,
            oceanFloorMinDepth,
            oceanFloorMaxDepth
         )
      );
   }

   private static StructureCategorySettings category(
      double supportThreshold,
      double footprintInsetRatio,
      int searchRadiusChunks,
      int minStableTopCells,
      int topOffset,
      int localSearchStepBlocks,
      int localSearchRadiusBlocks,
      double groundedSampleThreshold,
      int maxGroundGapBlocks,
      int minHostIslandRadius,
      int minHostStableTopCells
   ) {
      return new StructureCategorySettings(
         supportThreshold,
         footprintInsetRatio,
         searchRadiusChunks,
         minStableTopCells,
         topOffset,
         localSearchStepBlocks,
         localSearchRadiusBlocks,
         groundedSampleThreshold,
         maxGroundGapBlocks,
         minHostIslandRadius,
         minHostStableTopCells
      );
   }
}
