import { readPackSettings } from "../config/SkyIslandSettings.js";
export const Archetype=Object.freeze({CLASSIC:"classic",BOWL_CRATER:"bowl_crater",CRESCENT:"crescent",TERRACE:"terrace"});
export const Family=Object.freeze({ANCHOR:"anchor",SATELLITE:"satellite",SPIRE:"spire"});
export class IslandClusterSampler{
 constructor(noise,settings=readPackSettings()){this.noise=noise;this.settings=settings;}
 get s(){return this.settings;}
 heightBand(cx,cz){const s=this.s,t=(s.lowWeight??1)+(s.midHighWeight??3)+(s.veryHighWeight??1);let r=this.noise.sampleCell(cx,cz,240)*t;if(r<(s.lowWeight??1))return"low";r-=s.lowWeight??1;return r<(s.midHighWeight??3)?"mid_high":"very_high";}
 heightProfile(b){const s=this.s,min=s.minIslandY,max=s.maxIslandY,span=Math.max(24,max-min),lw=Math.max(12,span/5),hw=Math.max(12,span/6),midMin=min+Math.max(12,span/5),midMax=max-Math.max(12,span/6),lc=Math.max(min+lw/2,Math.min(midMin-8,min+Math.max(10,span/6))),hc=Math.min(max-hw/2,Math.max(midMax+8,max-Math.max(8,span/9)));if(b==="low")return[min,Math.min(max,Math.max(min+8,lc+lw/2))];if(b==="mid_high")return[Math.max(min,Math.min(midMin,lc+lw/2+4)),Math.min(max,Math.max(min+12,Math.max(midMax,hc-hw/2-4)))];return[Math.max(min,Math.min(max-8,hc-hw/2)),max];}
 cluster(cx,cz,seed,spacing=this.s.spacing){const s=this.s,half=spacing/2,jitter=Math.max(10,spacing/3),band=this.heightBand(cx,cz),[minY,maxY]=this.heightProfile(band),centerX=cx*spacing+half+this.noise.sampleCellInt(cx,cz,163,-jitter,jitter),centerZ=cz*spacing+half+this.noise.sampleCellInt(cx,cz,197,-jitter,jitter),centerY=this.noise.sampleCellInt(cx,cz,223,minY,maxY),tierRoll=this.noise.sampleCell(cx,cz,131),tier=tierRoll<.18?"grand":tierRoll<.72?"standard":"scattered";let sat=tier==="grand"?this.noise.sampleCellInt(cx,cz,281,5,8):tier==="standard"?this.noise.sampleCellInt(cx,cz,281,3,6):this.noise.sampleCellInt(cx,cz,281,2,4);sat=Math.max(band==="low"?1:2,sat+(band==="low"?-1:band==="very_high"&&tier==="grand"?1:0));let sp=tier==="grand"?this.noise.sampleCellInt(cx,cz,307,1,2):this.noise.sampleCellInt(cx,cz,307,0,1);sp=Math.max(0,Math.min(3,sp+(band==="low"?-1:band==="very_high"?1:0)));const weights=[s.classicWeight??1,s.bowlCraterWeight??1,s.crescentWeight??1,s.terraceWeight??1],sum=weights.reduce((a,b)=>a+b,0)||1;let target=this.noise.sampleCell(cx,cz,463)*sum,arch=Archetype.CLASSIC;for(const[k,w]of[[Archetype.CLASSIC,weights[0]],[Archetype.BOWL_CRATER,weights[1]],[Archetype.CRESCENT,weights[2]],[Archetype.TERRACE,weights[3]]]){if(target<w){arch=k;break;}target-=w;}return{cx,cz,centerX,centerY,centerZ,band,tier,baseRotation:this.noise.sampleCell(cx,cz,251)*Math.PI*2,archetype:arch,satelliteCount:sat,spireCount:sp,seed:mix(seed,cx,cz)};}
}
function mix(seed,x,z){return BigInt.asIntN(64,BigInt(seed)^BigInt(x)*-7046029254386353131n^BigInt(z)*-4417276706812531889n);}
