import { IslandNoise } from "./IslandNoise.js";
import { Archetype, Family } from "./IslandClusterSampler.js";
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class IslandShapeSampler {
 constructor(noise){this.noise=noise;}
 sample(d,x,z){const sin=Math.sin(d.rotation),cos=Math.cos(d.rotation),dx=x-d.x,dz=z-d.z;const wx=this.noise.fbm2D(d.seed+BigInt(13),x*.026,z*.026,3,.52)*d.rx*.14,wz=this.noise.fbm2D(d.seed+BigInt(17),x*.026,z*.026,3,.52)*d.rz*.14;const lx=(dx+wx)*cos+(dz+wz)*sin,lz=(dz+wz)*cos-(dx+wx)*sin;const bias=Math.cos(d.rotation+this.noise.sampleRange(d.seed,79,-.85,.85))*lx+Math.sin(d.rotation+this.noise.sampleRange(d.seed,83,-.85,.85))*lz,asym=bias/Math.max(10,d.maxR),rx=d.rx*(1+clamp(asym*.24,-.18,.34)),rz=d.rz*(1-clamp(asym*.18,-.2,.18));const primary=IslandNoise.ellipseDensity(lx,lz,rx,rz);let combined=primary;const crescent=d.family===Family.ANCHOR&&d.archetype===Archetype.CRESCENT;if(d.family===Family.ANCHOR&&!crescent){if(d.archetype===Archetype.BOWL_CRATER){const rim=IslandNoise.ellipseDensity(lx,lz,d.rx*1.02,d.rz*1.02),crater=Math.max(0,IslandNoise.ellipseDensity(lx,lz,d.rx*.46,d.rz*.46));combined=Math.max(primary,rim*.92)-crater*.66;}else if(d.archetype===Archetype.TERRACE){const u=IslandNoise.ellipseDensity(lx,lz,d.rx*.82,d.rz*.82),m=IslandNoise.ellipseDensity(lx,lz,d.rx*1.02,d.rz*1.02);combined=Math.max(primary*.95,Math.max(u*.86,m));}}
 const allow=!crescent;
 for(let i=0;i<d.lobes&&allow;i++){const s=IslandNoise.mix(d.seed,i,1409),a=d.rotation+this.noise.sampleRange(s,5,0,Math.PI*2),dist=this.noise.sampleRange(s,7,.18,.86)*Math.min(d.rx,d.rz),ox=Math.cos(a)*dist,oz=Math.sin(a)*dist,lrx=d.rx*this.noise.sampleRange(s,11,.3,d.family===Family.ANCHOR?.74:.54),lrz=d.rz*this.noise.sampleRange(s,13,.3,d.family===Family.ANCHOR?.74:.54),w=this.noise.sampleRange(s,17,.28,d.family===Family.ANCHOR?.74:.5);combined=Math.max(combined,primary*.58+IslandNoise.ellipseDensity(lx-ox,lz-oz,lrx,lrz)*w);}
 for(let i=0;i<d.peninsulas&&allow;i++){const s=IslandNoise.mix(d.seed,i,1709),a=d.rotation+this.noise.sampleRange(s,5,0,Math.PI*2),dist=this.noise.sampleRange(s,7,.74,1.18)*Math.max(d.rx,d.rz),ox=Math.cos(a)*dist,oz=Math.sin(a)*dist;const p=IslandNoise.ellipseDensity(lx-ox,lz-oz,d.rx*this.noise.sampleRange(s,11,.14,.28),d.rz*this.noise.sampleRange(s,13,.14,.28));combined=Math.max(combined,primary*.34+p*this.noise.sampleRange(s,17,.44,.72));}
 const shelf=IslandNoise.ellipseDensity(lx-d.hangX*.55,lz-d.hangZ*.55,d.tailX*1.35,d.tailZ*1.35);combined=Math.max(combined,primary*(allow?.72:.86)+shelf*(allow?.26:.1));
 for(let i=0;i<d.bites&&allow;i++){const s=IslandNoise.mix(d.seed,i,1901),a=d.rotation+this.noise.sampleRange(s,5,0,Math.PI*2),dist=this.noise.sampleRange(s,7,.56,1.06)*Math.min(d.rx,d.rz),p=IslandNoise.ellipseDensity(lx-Math.cos(a)*dist,lz-Math.sin(a)*dist,d.rx*this.noise.sampleRange(s,11,.16,.28),d.rz*this.noise.sampleRange(s,13,.16,.28));combined-=Math.max(0,p)*this.noise.sampleRange(s,17,.24,.54);}
 const macro=this.noise.fbm2D(d.seed+13n,x*.01,z*.01,4,.52),ridge=this.noise.ridgedFbm2D(d.seed+26n,x*.03,z*.03,3,.56),coast=this.noise.ridgedFbm2D(d.seed+31n,x*.046,z*.046,3,.55),split=this.noise.fbm2D(d.seed+341n,x*.032,z*.032,3,.53),edge=1-clamp(combined,0,1),erosion=Math.max(0,coast-d.erosion)*(.65+edge*.9)+Math.max(0,split-.36)*edge*.32;let coverage=combined+macro*.16+ridge*.1-erosion;if(crescent){const outer=IslandNoise.ellipseDensity(lx,lz,d.rx*1.16,d.rz*1.1),inner=Math.max(0,IslandNoise.ellipseDensity(lx-d.rx*.38,lz,d.rx*.78,d.rz*.58)),back=Math.max(0,IslandNoise.ellipseDensity(lx+d.rx*.34,lz,d.rx*.76,d.rz*.98))*clamp((-lx/d.rx+.34)/1.04,0,1),horn=Math.max(IslandNoise.ellipseDensity(lx-d.rx*.56,lz-d.rz*.86,d.rx*.58,d.rz*.3),IslandNoise.ellipseDensity(lx-d.rx*.56,lz+d.rz*.86,d.rx*.58,d.rz*.3));const opening=clamp((lx/d.rx+.08)/.82,0,1)*clamp(1-Math.abs(lz)/(d.rz*.4),0,1);coverage=Math.max(outer*1.08+back*.58+horn*.86-inner*1.08-opening*.36,IslandNoise.ellipseDensity(lx+d.rx*.26-d.hangX*.2,lz-d.hangZ*.2,d.rx*.92,d.rz*.92)*.54)-clamp(inner*1.04+opening*.62-outer*.3-horn*.34,0,1)*1.18;}
 return {lx,lz,coverage,edgeDistance:edge,branchCoverage:0,influence:coverage>-.28};}
}
