import { world, system } from "@minecraft/server";
import { readPackSettings } from "../config/SkyIslandSettings.js";
import { IslandNoise } from "./IslandNoise.js";
import { IslandClusterSampler } from "./IslandClusterSampler.js";
import { IslandDescriptorFactory } from "./IslandDescriptorFactory.js";
import { IslandShapeSampler } from "./IslandShapeSampler.js";
import { IslandDensityEvaluator } from "./IslandDensityEvaluator.js";
import { planColumn } from "./ExactMaterialPlan.js";
import { ExactSurfacePipeline } from "./ExactSurfacePipeline.js";
import { terrainProfile } from "./BiomeTerrainProfiles.js";
import { StructureDetection } from "./StructureDetection.js";
import { StructurePlacement } from "./StructurePlacement.js";
import { StructureRegistry, StructureCategory } from "./StructureRegistry.js";
import { StructureOverlapGuard } from "./StructureOverlapGuard.js";
import { NativeStructureCoordinator } from "./NativeStructureCoordinator.js";

const DB = "sky_archipelago:generated_v12";
const DIMENSION = "sky_archipelago:archipelago";
const WATER = "minecraft:water";
const CATEGORY_CONFIG = Object.freeze({
  [StructureCategory.SMALL_SKY]: { family: "ruined_portal/", maxDepth: 1, chance: 0.010 },
  [StructureCategory.SURFACE_SKY]: { family: "pillageroutpost/", maxDepth: 1, chance: 0.008 },
  [StructureCategory.GROUND_VILLAGE]: { family: "village/", maxDepth: 7, chance: 0.012 },
  [StructureCategory.WATER]: { family: "shipwreck/", maxDepth: 1, chance: 0.004 },
  [StructureCategory.UNDERGROUND]: { family: "ancient_city/", maxDepth: 1, chance: 0.002 },
  [StructureCategory.STRONGHOLD]: { family: null, maxDepth: 0, chance: 0.0008 },
});

export class IslandGenerator {
  constructor() { this.noise=null;this.clusters=null;this.factory=null;this.shape=null;this.density=null;this.settings=null;this.generated=new Set();this.queue=[];this.queued=new Set();this.jobs=[];this.layoutSeed=0n;this.surface=null;this.structures=null;this.placement=null;this.registry=null;this.structureJobs=[];this.placedStructureKeys=new Set();this.overlap=new StructureOverlapGuard();this.native=null;this.state=new Map();this.activeJob=null; }

  load() {
    if (this.noise) return;
    this.settings=readPackSettings();this.layoutSeed=BigInt(world.seed);this.noise=new IslandNoise(this.layoutSeed);this.clusters=new IslandClusterSampler(this.noise,this.settings);this.factory=new IslandDescriptorFactory(this.noise);this.shape=new IslandShapeSampler(this.noise);this.density=new IslandDensityEvaluator(this.noise,this.shape);this.surface=new ExactSurfacePipeline(this.settings,this.noise);this.structures=new StructureDetection(this.settings);this.placement=new StructurePlacement(this.structures,{generator:this,overlapGuard:this.overlap});this.registry=new StructureRegistry();this.registry.refresh();this.native=new NativeStructureCoordinator(this,null);this.overlap.load();
    try { const raw=world.getDynamicProperty(DB);if(typeof raw==="string"){const d=JSON.parse(raw);if(d.seed===this.layoutSeed.toString()&&d.settingsHash===this.settingsHash()){this.generated=new Set(d.generated||[]);this.placedStructureKeys=new Set(d.placedStructureKeys||[]);this.state=new Map(d.state||[]);this.structureJobs=d.structureJobs||[];}} } catch(e){console.warn(`[Sky Archipelago] persistence load failed: ${e}`);}
    for(const [k,v] of this.state) if(v!=="COMPLETE"&&!this.queued.has(k)){const [cx,cz]=k.split(",").map(Number);this.queued.add(k);this.queue.push({cx,cz});}
  }
  settingsHash(){return JSON.stringify(this.settings);} save(){try{world.setDynamicProperty(DB,JSON.stringify({version:12,seed:this.layoutSeed.toString(),settingsHash:this.settingsHash(),generated:[...this.generated],placedStructureKeys:[...this.placedStructureKeys],state:[...this.state],structureJobs:this.structureJobs.slice(0,256)}));}catch(e){console.warn(`[Sky Archipelago] persistence save failed: ${e}`);}}
  cluster(cx,cz){return this.clusters.cluster(cx,cz,this.layoutSeed,this.settings.spacing);}
  descriptorsForCell(cx,cz){const c=this.cluster(cx,cz),out=[this.factory.anchor(c)];for(let i=0;i<c.satelliteCount;i++)out.push(this.factory.satellite(c,i));for(let i=0;i<c.spireCount;i++)out.push(this.factory.spire(c,i));const scale=Math.max(.35,Math.min(2.2,(this.settings.minIslandRadius/18+this.settings.maxIslandRadius/72)/2)),ss=this.settings.spacing/96;for(const d of out){d.x=c.centerX+(d.x-c.centerX)*ss;d.z=c.centerZ+(d.z-c.centerZ)*ss;d.rx=Math.max(4,d.rx*scale);d.rz=Math.max(4,d.rz*scale);d.maxR=Math.max(d.rx,d.rz);d.plateau=Math.max(2,d.plateau*this.settings.terrainReliefScale);d.cliff=Math.max(4,d.cliff*this.settings.terrainReliefScale);d.hang=Math.max(8,Math.min(this.settings.maxIslandThickness,d.hang));}return out;}
  descriptorsNear(x,z){const s=this.settings.spacing,cx=Math.floor(x/s),cz=Math.floor(z/s),out=[];for(let ix=cx-3;ix<=cx+3;ix++)for(let iz=cz-3;iz<=cz+3;iz++)for(const d of this.descriptorsForCell(ix,iz)){const reach=Math.max(d.maxR*3+96,Math.max(Math.abs(d.hangX)+d.tailX*2,Math.abs(d.hangZ)+d.tailZ*2)+96),dx=x-d.x,dz=z-d.z;if(dx*dx+dz*dz<=reach*reach)out.push(d);}return out;}
  column(x,z,minY=-64,maxY=320){const ds=this.descriptorsNear(x,z);if(!ds.length)return[];const raw=[];let active=false,top=0;for(let y=maxY-1;y>=minY;y--){let den=-Infinity;for(const d of ds){const h=this.shape.sample(d,x,z);if(h.influence)den=Math.max(den,this.density.density(d,h,x,y,z));}const solid=den>0;if(solid&&!active){top=y;active=true;}if(!solid&&active){raw.push([y+1,top]);active=false;}}if(active)raw.push([minY,top]);return this.resolveOverlapExact(raw);}
  resolveOverlapExact(raw){if(raw.length<2)return raw;const mode=this.settings.terrainOverlapMode;if(mode==="overlap")return raw;if(mode==="void")return[raw.reduce((a,b)=>a[1]>b[1]?a:b)];const sorted=[...raw].sort((a,b)=>b[1]-a[1]),keep=[sorted[0]];for(let i=1;i<sorted.length;i++){const lower=sorted[i],upper=keep[keep.length-1],gap=upper[0]-lower[1];if(gap>=8){const carving=Math.min(28,Math.max(2,Math.floor((upper[1]-upper[0]+1)*.5))),end=lower[1]-carving;if(end-lower[0]+1>=4)keep.push([lower[0],end]);}}return keep.sort((a,b)=>a[0]-b[0]);}
  biomeAt(dim,x,y,z){try{return dim.getBiome({x,y,z})?.id??"minecraft:plains";}catch{return"minecraft:plains";}}
  generateColumn(dim,x,z,segments){if(!segments.length)return;const top=Math.max(...segments.map(s=>s[1])),biome=this.biomeAt(dim,x,top,z),profile=terrainProfile(biome),plan=planColumn(segments,-64,321,{...this.settings,deepslateStartY:this.settings.deepslateStartY-(profile[0]-1)*3},x,z,this.layoutSeed);for(let y=-64;y<=320;y++){const p=plan.materialAt(y);if(p)dim.setBlockPermutation({x,y,z},p);else if(this.settings.oceanEnabled&&y<=plan.oceanTop&&y>top)dim.setBlockType({x,y,z},WATER);else if(y>=top+1)dim.setBlockType({x,y,z},"minecraft:air");}this.surface.apply(dim,x,z,segments,biome,profile,this.layoutSeed);}
  structureSeed(x,z,type="template"){let v=this.layoutSeed^BigInt(Math.trunc(x)*0x9E3779B1)^BigInt(Math.trunc(z)*0x85EBCA77);for(const c of String(type))v^=BigInt(c.charCodeAt(0));v^=v>>33n;v*=0xff51afd7ed558ccdn;v^=v>>33n;return Number(v&0x7fffffffn)/0x80000000;}
  chooseStructure(d){const r=this.structureSeed(Math.floor(d.x),Math.floor(d.z),"structure"),nativeR=this.structureSeed(Math.floor(d.x),Math.floor(d.z),"native");if(nativeR<0.00025)return{native:"stronghold",category:StructureCategory.STRONGHOLD};if(nativeR<0.001)return{native:"mineshaft",category:StructureCategory.UNDERGROUND};let cumulative=0;for(const[category,config]of Object.entries(CATEGORY_CONFIG)){if(category===StructureCategory.STRONGHOLD)continue;cumulative+=config.chance;if(r>=cumulative)continue;const entry=this.registry.select(Math.floor(r*0x7fffffff),category,config.family);if(entry)return{entry,category,maxDepth:config.maxDepth};}return null;}
  structureCandidate(x,z){const ds=this.descriptorsNear(x,z);if(!ds.length)return null;for(const d of ds){const dist=Math.hypot(x-d.x,z-d.z);if(dist>d.maxR*.8)continue;const selected=this.chooseStructure(d);if(!selected)continue;if(selected.native){const key=`native:${selected.native}:${Math.floor(d.x/16)}:${Math.floor(d.z/16)}`;if(this.placedStructureKeys.has(key))continue;return{id:selected.native,normalizedId:selected.native,key,x:Math.floor(d.x),z:Math.floor(d.z),y:Math.floor(d.plateau||128),category:selected.category,native:true};}const entry=selected.entry,key=`${entry.normalized}:${Math.floor(d.x/16)}:${Math.floor(d.z/16)}`;if(this.placedStructureKeys.has(key))continue;return{id:entry.id,normalizedId:entry.normalized,key,x:Math.floor(d.x),z:Math.floor(d.z),y:Math.max(0,Math.floor(d.plateau||128)),category:selected.category,maxDepth:selected.maxDepth,family:entry.family};}return null;}
  queueStructuresForChunk(cx,cz){for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++){const c=this.structureCandidate(cx*16+8+dx*16,cz*16+8+dz*16);if(c&&!this.structureJobs.some(j=>j.key===c.key))this.structureJobs.push(c);}}
  placeQueuedStructures(){if(!this.structureJobs.length)return;const dim=world.getDimension(DIMENSION),job=this.structureJobs.shift();try{let r=null;if(job.native==="stronghold"){const plan=this.native.plan("stronghold",{x:job.x,y:job.y,z:job.z,footprint:{x:48,y:32,z:48}});r=this.native.commit("stronghold",plan);}else if(job.native==="mineshaft"){const plan=this.native.plan("mineshaft",{x:job.x,y:job.y,z:job.z,footprint:{x:64,y:24,z:64}});r=this.native.commit("mineshaft",plan);}else if(job.category===StructureCategory.GROUND_VILLAGE)r=this.placement.placeJigsawStructure(job.id,dim,{x:job.x,y:job.y,z:job.z},{maxDepth:job.maxDepth},1);else if(job.category===StructureCategory.UNDERGROUND)r=this.placement.placeTemplate(job.id,dim,{x:job.x,y:Math.max(-64,job.y-24),z:job.z},{rotation:"None"},4);else if(job.category===StructureCategory.WATER)r=this.placement.placeTemplate(job.id,dim,{x:job.x,y:Math.max(0,job.y-6),z:job.z},{rotation:"None"},3);else r=this.placement.placeTemplate(job.id,dim,{x:job.x,y:job.y,z:job.z},{rotation:"None"},1);if(r?.placed||r?.accepted){this.placedStructureKeys.add(job.key);this.save();}}catch(e){console.warn(`[Sky Archipelago] structure placement failed for ${job.id}: ${e}`);}}
  scanStructures(dim,player){if(!this.structures)return;for(const s of this.structures.scan(dim,player.location.x,player.location.z,6))this.structures.apply(dim,s);}
  enqueue(cx,cz){const k=`${cx},${cz}`;if(this.generated.has(k)||this.queued.has(k))return;this.queued.add(k);this.state.set(k,"QUEUED");this.queue.push({cx,cz});}
  requestAround(player){this.load();const cx=Math.floor(player.location.x/16),cz=Math.floor(player.location.z/16);for(let dx=-8;dx<=8;dx++)for(let dz=-8;dz<=8;dz++)this.enqueue(cx+dx,cz+dz);this.queue.sort((a,b)=>((a.cx-cx)**2+(a.cz-cz)**2)-((b.cx-cx)**2+(b.cz-cz)**2));this.queueStructuresForChunk(cx,cz);this.scanStructures(world.getDimension(DIMENSION),player);this.save();}
  startNext(){if(this.jobs.length||!this.queue.length)return;const q=this.queue.shift(),k=`${q.cx},${q.cz}`;this.state.set(k,"GENERATING");this.jobs.push({cx:q.cx,cz:q.cz,x:0,z:0});this.save();}
  tick(){this.load();this.placeQueuedStructures();this.startNext();const j=this.jobs[0];if(!j)return;const dim=world.getDimension(DIMENSION);let count=0;while(count<4&&j.x<16){const x=j.cx*16+j.x,z=j.cz*16+j.z;this.generateColumn(dim,x,z,this.column(x,z));j.z++;count++;if(j.z>=16){j.z=0;j.x++;}}if(j.x>=16){const k=`${j.cx},${j.cz}`;this.generated.add(k);this.queued.delete(k);this.state.set(k,"COMPLETE");this.jobs.shift();this.save();}}
  reset(){this.generated.clear();this.queue=[];this.queued.clear();this.jobs=[];this.structureJobs=[];this.placedStructureKeys.clear();this.state.clear();this.overlap.clear();this.save();}
}
