import { world } from "@minecraft/server";
import { readPackSettings } from "../config/SkyIslandSettings.js";
import { IslandNoise } from "./IslandNoise.js";
import { IslandClusterSampler } from "./IslandClusterSampler.js";
import { IslandDescriptorFactory } from "./IslandDescriptorFactory.js";
import { IslandShapeSampler } from "./IslandShapeSampler.js";
import { IslandDensityEvaluator } from "./IslandDensityEvaluator.js";
import { planColumn } from "./ExactMaterialPlan.js";
import { ExactSurfacePipeline } from "./ExactSurfacePipeline.js";
import { terrainProfile } from "./BiomeTerrainProfiles.js";
import { StructureDetection } from "./StructureDetection.js";
const DB="sky_archipelago:generated_v9",DIMENSION="sky_archipelago:archipelago",WATER="minecraft:water";
export class IslandGenerator{
constructor(){this.noise=null;this.clusters=null;this.factory=null;this.shape=null;this.density=null;this.settings=null;this.generated=new Set;this.queue=[];this.queued=new Set;this.jobs=[];this.layoutSeed=0n;this.surface=null;this.structures=null;}
load(){if(this.noise)return;this.settings=readPackSettings();this.layoutSeed=BigInt(world.seed);this.noise=new IslandNoise(this.layoutSeed);this.clusters=new IslandClusterSampler(this.noise,this.settings);this.factory=new IslandDescriptorFactory(this.noise);this.shape=new IslandShapeSampler(this.noise);this.density=new IslandDensityEvaluator(this.noise,this.shape);this.surface=new ExactSurfacePipeline(this.settings,this.noise);this.structures=new StructureDetection(this.settings);try{const raw=world.getDynamicProperty(DB);if(typeof raw==="string"){const d=JSON.parse(raw);if(d.seed===this.layoutSeed.toString()&&d.settingsHash===this.settingsHash())this.generated=new Set(d.generated)}}catch(e){console.warn(`[Sky Archipelago] persistence load failed: ${e}`)}}
settingsHash(){return JSON.stringify(this.settings)}save(){world.setDynamicProperty(DB,JSON.stringify({version:9,seed:this.layoutSeed.toString(),settingsHash:this.settingsHash(),generated:[...this.generated]}))}
cluster(cx,cz){return this.clusters.cluster(cx,cz,this.layoutSeed,this.settings.spacing)}
descriptorsForCell(cx,cz){const c=this.cluster(cx,cz),out=[this.factory.anchor(c)];for(let i=0;i<c.satelliteCount;i++)out.push(this.factory.satellite(c,i));for(let i=0;i<c.spireCount;i++)out.push(this.factory.spire(c,i));const scale=Math.max(.35,Math.min(2.2,(this.settings.minIslandRadius/18+this.settings.maxIslandRadius/72)/2)),ss=this.settings.spacing/96;for(const d of out){d.x=c.centerX+(d.x-c.centerX)*ss;d.z=c.centerZ+(d.z-c.centerZ)*ss;d.rx=Math.max(4,d.rx*scale);d.rz=Math.max(4,d.rz*scale);d.maxR=Math.max(d.rx,d.rz);d.plateau=Math.max(2,d.plateau*this.settings.terrainReliefScale);d.cliff=Math.max(4,d.cliff*this.settings.terrainReliefScale);d.hang=Math.max(8,Math.min(this.settings.maxIslandThickness,d.hang))}return out}
descriptorsNear(x,z){const s=this.settings.spacing,cx=Math.floor(x/s),cz=Math.floor(z/s),out=[];for(let ix=cx-3;ix<=cx+3;ix++)for(let iz=cz-3;iz<=cz+3;iz++)for(const d of this.descriptorsForCell(ix,iz)){const reach=Math.max(d.maxR*3+96,Math.max(Math.abs(d.hangX)+d.tailX*2,Math.abs(d.hangZ)+d.tailZ*2)+96),dx=x-d.x,dz=z-d.z;if(dx*dx+dz*dz<=reach*reach)out.push(d)}return out}
column(x,z,minY=-64,maxY=320){const ds=this.descriptorsNear(x,z);if(!ds.length)return[];const raw=[];let active=false,top=0;for(let y=maxY-1;y>=minY;y--){let den=-Infinity;for(const d of ds){const h=this.shape.sample(d,x,z);if(h.influence)den=Math.max(den,this.density.density(d,h,x,y,z))}const solid=den>0;if(solid&&!active){top=y;active=true}if(!solid&&active){raw.push([y+1,top]);active=false}}if(active)raw.push([minY,top]);return this.resolveOverlapExact(raw)}
resolveOverlapExact(raw){if(raw.length<2)return raw;const mode=this.settings.terrainOverlapMode;if(mode==="overlap")return raw;if(mode==="void")return[raw.reduce((a,b)=>a[1]>b[1]?a:b)];const sorted=[...raw].sort((a,b)=>b[1]-a[1]),keep=[sorted[0]];for(let i=1;i<sorted.length;i++){const lower=sorted[i],upper=keep[keep.length-1],gap=upper[0]-lower[1];if(gap>=8){const carving=Math.min(28,Math.max(2,Math.floor((upper[1]-upper[0]+1)*.5))),end=lower[1]-carving;if(end-lower[0]+1>=4)keep.push([lower[0],end])}}return keep.sort((a,b)=>a[0]-b[0])}
biomeAt(dim,x,y,z){try{return dim.getBiome({x,y,z})?.id??"minecraft:plains"}catch{return"minecraft:plains"}}
generateColumn(dim,x,z,segments){if(!segments.length)return;const top=Math.max(...segments.map(s=>s[1])),biome=this.biomeAt(dim,x,top,z),profile=terrainProfile(biome),plan=planColumn(segments,-64,321,{...this.settings,deepslateStartY:this.settings.deepslateStartY-(profile[0]-1)*3},x,z,this.layoutSeed);for(let y=-64;y<=320;y++){const p=plan.materialAt(y);if(p)dim.setBlockPermutation({x,y,z},p);else if(this.settings.oceanEnabled&&y<=plan.oceanTop&&y>top)dim.setBlockType({x,y,z},WATER);else if(y>=top+1)dim.setBlockType({x,y,z},"minecraft:air")}this.surface.apply(dim,x,z,segments,biome,profile,this.layoutSeed)}
scanStructures(dim,player){if(!this.structures)return;for(const s of this.structures.scan(dim,player.location.x,player.location.z,6))this.structures.apply(dim,s)}
enqueue(cx,cz){const k=`${cx},${cz}`;if(this.generated.has(k)||this.queued.has(k))return;this.queued.add(k);this.queue.push({cx,cz})}
requestAround(player){this.load();const cx=Math.floor(player.location.x/16),cz=Math.floor(player.location.z/16);for(let dx=-8;dx<=8;dx++)for(let dz=-8;dz<=8;dz++)this.enqueue(cx+dx,cz+dz);this.queue.sort((a,b)=>((a.cx-cx)**2+(a.cz-cz)**2)-((b.cx-cx)**2+(b.cz-cz)**2));this.scanStructures(world.getDimension(DIMENSION),player)}
startNext(){if(this.jobs.length||!this.queue.length)return;const q=this.queue.shift();this.jobs.push({cx:q.cx,cz:q.cz,x:0,z:0})}
tick(){this.load();this.startNext();const j=this.jobs[0];if(!j)return;const dim=world.getDimension(DIMENSION);let count=0;while(count<4&&j.x<16){const x=j.cx*16+j.x,z=j.cz*16+j.z;this.generateColumn(dim,x,z,this.column(x,z));j.z++;count++;if(j.z>=16){j.z=0;j.x++}}if(j.x>=16){const k=`${j.cx},${j.cz}`;this.generated.add(k);this.queued.delete(k);this.jobs.shift();this.save()}}
reset(){this.generated.clear();this.queue=[];this.queued.clear();this.jobs=[];this.save()}}
