import { SETTINGS } from "../config/SkyIslandSettings.js";
import { Archetype, Family } from "./IslandClusterSampler.js";

const mix=(s,x,z)=>BigInt.asIntN(64,BigInt(s)^BigInt(x)*-7046029254386353131n^BigInt(z)*-4417276706812531889n);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

export class IslandDescriptorFactory {
 constructor(noise){this.noise=noise;}
 cap(a,b,c){const max=SETTINGS.maxIslandThickness;const total=a+b+c;if(total<=max)return[a,b,c];const scale=(max-8)/total;return[Math.max(3,Math.floor(a*scale)),Math.max(8,Math.floor(b*scale)),Math.max(12,Math.floor(c*scale))];}
 anchor(c){const n=this.noise,s=SETTINGS,min=s.minIslandRadius,max=s.maxIslandRadius;const familyScale=(c.tier==="grand"?1.55:c.tier==="standard"?1.18:.95)*(c.band==="low"?.88:c.band==="very_high"?1.1:1);let rx=Math.round(n.sampleRange(c.seed,11,min*familyScale,max*familyScale*1.18)),rz=Math.round(n.sampleRange(c.seed,13,min*familyScale,max*familyScale*1.18));if(c.archetype===Archetype.CRESCENT){const l=Math.max(rx,rz),q=Math.min(rx,rz);rx=Math.max(16,Math.round(l*1.05));rz=Math.max(16,Math.round(Math.max(q*1.02,l*.82)));}const vb=c.band==="low"?.9:c.band==="very_high"?1.08:1;let ph=Math.round(Math.max(12,(rx+rz)*.16+n.sampleRange(c.seed,17,6,14))*vb),cd=Math.round(Math.max(18,(rx+rz)*.22+n.sampleRange(c.seed,19,12,22))*vb),hd=Math.round(Math.max(24,Math.max(rx,rz)*.85+n.sampleRange(c.seed,23,20,44))*(c.band==="low"?.84:c.band==="very_high"?1.04:1));if(c.archetype===Archetype.CRESCENT){ph=Math.max(8,Math.round(ph*.15));cd=Math.max(12,Math.round(cd*.4));hd=Math.max(16,Math.round(hd*.45));} [ph,cd,hd]=this.cap(ph,cd,hd);let lx=n.sampleInt(c.seed,31,-Math.floor(rx/4),Math.floor(rx/4)),lz=n.sampleInt(c.seed,37,-Math.floor(rz/4),Math.floor(rz/4)),trX=Math.round(rx*n.sampleRange(c.seed,41,.34,.58)),trZ=Math.round(rz*n.sampleRange(c.seed,43,.34,.58));let erosion=n.sampleRange(c.seed,47,.32,.54),lob=6+n.sampleInt(c.seed,53,0,3),pen=4+n.sampleInt(c.seed,57,0,2),bite=4+n.sampleInt(c.seed,61,0,2);if(c.archetype===Archetype.CRESCENT){lx=n.sampleInt(c.seed,31,-Math.floor(rx/8),Math.floor(rx/8));lz=n.sampleInt(c.seed,37,-Math.floor(rz/8),Math.floor(rz/8));trX=Math.round(rx*n.sampleRange(c.seed,41,.26,.4));trZ=Math.round(rz*n.sampleRange(c.seed,43,.22,.36));erosion=n.sampleRange(c.seed,47,.4,.58);lob=pen=bite=0;}const rot=c.archetype===Archetype.CRESCENT?n.sampleInt(c.seed,89,0,7)*Math.PI/4+n.sampleRange(c.seed,97,-.16,.16):c.baseRotation+n.sampleRange(c.seed,29,-.45,.45);return {family:Family.ANCHOR,x:c.centerX,y:c.centerY,z:c.centerZ,rx,rz,maxR:Math.max(rx,rz),rotation:rot,archetype:c.archetype,plateau:ph,cliff:cd,hang:hd,hangX:lx,hangZ:lz,tailX:trX,tailZ:trZ,erosion,lobes:lob,peninsulas:pen,bites:bite,seed:BigInt(c.seed)^25214903917n};}
 satellite(c,i){const n=this.noise,seed=mix(c.seed,i,701),band=c.band,scale=n.sampleRange(seed,17,.46,.8)*(band==="low"?.9:band==="very_high"?1.06:1),orbit=n.sampleRange(seed,7,SETTINGS.minIslandRadius*1.6,SETTINGS.maxIslandRadius*2.8)+i*n.sampleRange(seed,11,4,10),angle=c.baseRotation+n.sampleRange(seed,5,.15,5.8119)+i*(c.archetype===Archetype.CRESCENT?.7:c.archetype===Archetype.TERRACE?.48:.55),mul=c.archetype===Archetype.BOWL_CRATER?1.1:c.archetype===Archetype.CRESCENT?1.06:c.archetype===Archetype.TERRACE?.92:1;const x=c.centerX+Math.floor(Math.cos(angle)*orbit*mul),z=c.centerZ+Math.floor(Math.sin(angle)*orbit*mul),rx=Math.max(10,Math.round(n.sampleRange(seed,19,SETTINGS.minIslandRadius*.58*scale,SETTINGS.maxIslandRadius*.62*scale))),rz=Math.max(10,Math.round(n.sampleRange(seed,23,SETTINGS.minIslandRadius*.52*scale,SETTINGS.maxIslandRadius*.7*scale)));let y=c.centerY+n.sampleInt(seed,13,-24,18)+(c.archetype===Archetype.BOWL_CRATER?4:c.archetype===Archetype.CRESCENT?2:c.archetype===Archetype.TERRACE?6:0);const [lo,hi]=this.band(c.band);y=clamp(y,lo+8,hi-8);let ph=Math.round(n.sampleRange(seed,29,6,12)*(band==="low"?.9:band==="very_high"?1.05:1)),cd=Math.round(n.sampleRange(seed,31,14,24)),hd=Math.round(Math.max(18,Math.max(rx,rz)*n.sampleRange(seed,37,.7,1.1)));[ph,cd,hd]=this.cap(ph,cd,hd);return {family:Family.SATELLITE,x,y,z,rx,rz,maxR:Math.max(rx,rz),rotation:n.sampleRange(seed,41,0,Math.PI*2),archetype:c.archetype,plateau:ph,cliff:cd,hang:hd,hangX:n.sampleInt(seed,43,-rx/3,rx/3),hangZ:n.sampleInt(seed,47,-rz/3,rz/3),tailX:Math.round(rx*n.sampleRange(seed,53,.24,.42)),tailZ:Math.round(rz*n.sampleRange(seed,59,.24,.42)),erosion:n.sampleRange(seed,61,.24,.46),lobes:4+n.sampleInt(seed,67,0,1),peninsulas:2+n.sampleInt(seed,71,0,1),bites:2+n.sampleInt(seed,73,0,2),seed};}
 spire(c,i){const n=this.noise,seed=mix(c.seed,i,911),band=c.band,angle=c.baseRotation+n.sampleRange(seed,3,0,Math.PI*2)+(c.archetype===Archetype.CRESCENT?(i===0?-.55:.55):0),orbit=n.sampleRange(seed,5,SETTINGS.minIslandRadius*1.4,SETTINGS.maxIslandRadius*2.4)*(c.archetype===Archetype.BOWL_CRATER?1.14:c.archetype===Archetype.CRESCENT?1.12:c.archetype===Archetype.TERRACE?.88:1),[lo,hi]=this.band(band),x=c.centerX+Math.floor(Math.cos(angle)*orbit),z=c.centerZ+Math.floor(Math.sin(angle)*orbit),y=clamp(c.centerY+n.sampleInt(seed,7,-12,34),lo+6,hi-6),rx=Math.max(8,n.sampleInt(seed,11,8,Math.max(12,SETTINGS.minIslandRadius/2))),rz=Math.max(8,n.sampleInt(seed,13,8,Math.max(12,SETTINGS.minIslandRadius/2+4))),ph=n.sampleInt(seed,17,3,7),cd=n.sampleInt(seed,19,10,18),hd=n.sampleInt(seed,23,Math.max(24,SETTINGS.minIslandRadius),Math.max(36,SETTINGS.maxIslandRadius+18));return {family:Family.SPIRE,x,y,z,rx,rz,maxR:Math.max(rx,rz),rotation:n.sampleRange(seed,29,0,Math.PI*2),archetype:c.archetype,plateau:ph,cliff:cd,hang:hd,hangX:n.sampleInt(seed,31,-rx/4,rx/4),hangZ:n.sampleInt(seed,37,-rz/4,rz/4),tailX:rx*.3,tailZ:rz*.3,erosion:.3,lobes:2,peninsulas:1,bites:1,seed};}
 band(b){return b==="low"?[SETTINGS.minIslandY,SETTINGS.minIslandY+(SETTINGS.maxIslandY-SETTINGS.minIslandY)*.3]:b==="very_high"?[SETTINGS.minIslandY+(SETTINGS.maxIslandY-SETTINGS.minIslandY)*.7,SETTINGS.maxIslandY]:[SETTINGS.minIslandY+(SETTINGS.maxIslandY-SETTINGS.minIslandY)*.2,SETTINGS.minIslandY+(SETTINGS.maxIslandY-SETTINGS.minIslandY)*.85];}
}
