import { world } from "@minecraft/server";
import { readPackSettings } from "../config/SkyIslandSettings.js";
import { IslandNoise } from "./IslandNoise.js";
import { IslandClusterSampler } from "./IslandClusterSampler.js";
import { IslandDescriptorFactory } from "./IslandDescriptorFactory.js";
import { IslandShapeSampler } from "./IslandShapeSampler.js";
import { IslandDensityEvaluator } from "./IslandDensityEvaluator.js";
import { planColumn } from "./ExactMaterialPlan.js";
import { ExactSurfacePipeline } from "./ExactSurfacePipeline.js";
import { terrainProfile } from "./BiomeTerrainProfiles.js";
import { StructureDetection } from "./StructureDetection.js";
import { StructurePlacement } from "./StructurePlacement.js";
import { StructureRegistry, StructureCategory } from "./StructureRegistry.js";
import { StructureOverlapGuard } from "./StructureOverlapGuard.js";
import { NativeStructureCoordinator } from "./NativeStructureCoordinator.js";
import { TerrainAdaptationEngine } from "./TerrainAdaptationEngine.js";
import { assetRole } from "./StructureAssetMapping.js";

const DB="sky_archipelago:generated_v14",DIMENSION="sky_archipelago:archipelago",WATER="minecraft:water";
const WORLD_MIN_Y=-64,WORLD_MAX_Y=320,MAX_NEAR_DESCRIPTOR_CACHE=4096,MAX_STRUCTURE_CANDIDATE_CACHE=2048,SPAWN_RADIUS_CHUNKS=8;
const MAX_DYNAMIC_PROPERTY_LENGTH=32767,MAX_PERSISTED_GENERATED=9000,MAX_PERSISTED_STATES=7000,MAX_PERSISTED_STRUCTURES=1500,MAX_PERSISTENCE_RETRY_MS=5000;
const DEFAULT_SETTINGS={spacing:96,minIslandRadius:16,maxIslandRadius:72,terrainReliefScale:1,maxIslandThickness:96,minIslandY:32,maxIslandY:192,deepslateStartY:0,terrainOverlapMode:"carve",oceanEnabled:false};
const CATEGORY_CONFIG=Object.freeze({
 [StructureCategory.SMALL_SKY]:[{family:"ruined_portal/",maxDepth:1,chance:.006},{family:"igloo/",maxDepth:1,chance:.002}],
 [StructureCategory.SURFACE_SKY]:[{family:"pillageroutpost/",maxDepth:1,chance:.006},{family:"endcity/",maxDepth:8,chance:.002},{family:"mansion/",maxDepth:1,chance:.0008},{family:"bastion/",maxDepth:4,chance:.002}],
 [StructureCategory.GROUND_VILLAGE]:[{family:"village/",maxDepth:7,chance:.010},{family:"trail_ruins/",maxDepth:4,chance:.002}],
 [StructureCategory.WATER]:[{family:"shipwreck/",maxDepth:1,chance:.0025},{family:"ruin/",maxDepth:1,chance:.002},{family:"underwater_ruin/",maxDepth:1,chance:.002},{family:"coralcrust/",maxDepth:1,chance:.001}],
 [StructureCategory.UNDERGROUND]:[{family:"ancient_city/",maxDepth:1,chance:.002},{family:"trial_chambers/",maxDepth:8,chance:.0015},{family:"fossils/",maxDepth:1,chance:.0015},{family:"nether_fossils/",maxDepth:1,chance:.0008}]
});
const NATIVE_STRUCTURE_CHANCES=Object.freeze([{id:"monument",category:StructureCategory.WATER,chance:.00035,footprint:{x:56,y:24,z:56}},{id:"stronghold",category:StructureCategory.STRONGHOLD,chance:.00020,footprint:{x:96,y:48,z:96}},{id:"mineshaft",category:StructureCategory.UNDERGROUND,chance:.00055,footprint:{x:64,y:24,z:64}}]);
function finite(value,fallback){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function positive(value,fallback){const n=finite(value,fallback);return n>0?n:fallback;}
function sanitizeSettings(raw){const s={...DEFAULT_SETTINGS,...(raw&&typeof raw==="object"?raw:{})};s.spacing=positive(s.spacing,DEFAULT_SETTINGS.spacing);s.minIslandRadius=positive(s.minIslandRadius,DEFAULT_SETTINGS.minIslandRadius);s.maxIslandRadius=Math.max(s.minIslandRadius,positive(s.maxIslandRadius,DEFAULT_SETTINGS.maxIslandRadius));s.terrainReliefScale=positive(s.terrainReliefScale,DEFAULT_SETTINGS.terrainReliefScale);s.maxIslandThickness=positive(s.maxIslandThickness,DEFAULT_SETTINGS.maxIslandThickness);s.minIslandY=finite(s.minIslandY,DEFAULT_SETTINGS.minIslandY);s.maxIslandY=Math.max(s.minIslandY,finite(s.maxIslandY,DEFAULT_SETTINGS.maxIslandY));s.deepslateStartY=finite(s.deepslateStartY,DEFAULT_SETTINGS.deepslateStartY);return s;}
function safeSeed(value){if(typeof value==="bigint")return value;if(typeof value==="number"&&Number.isFinite(value)&&Number.isSafeInteger(value))return BigInt(value);if(typeof value==="string"&&/^-?\d+$/.test(value))return BigInt(value);return 0n;}
function flattenCategoryConfig(){const out=[];for(const [category,entries]of Object.entries(CATEGORY_CONFIG))for(const entry of entries)out.push({...entry,category});return out;}
const ALL_STRUCTURE_CONFIG=Object.freeze(flattenCategoryConfig());
function normalizeBounds(value){if(!value)return null;if(value.minX!=null)return{minX:Number(value.minX),minY:Number(value.minY),minZ:Number(value.minZ),maxX:Number(value.maxX),maxY:Number(value.maxY),maxZ:Number(value.maxZ)};if(value.min&&value.max)return{minX:Number(value.min.x),minY:Number(value.min.y),minZ:Number(value.min.z),maxX:Number(value.max.x),maxY:Number(value.max.y),maxZ:Number(value.max.z)};return null;}
function boundedSetCache(cache,key,value,maxSize){if(cache.has(key))cache.delete(key);cache.set(key,value);if(cache.size>maxSize)cache.delete(cache.keys().next().value);return value;}
function boundedGetCache(cache,key){const value=cache.get(key);if(value!==undefined){cache.delete(key);cache.set(key,value);}return value;}
function trimArray(arr,max){return arr.length<=max?arr:arr.slice(arr.length-max);}

export class IslandGenerator{
 constructor(){Object.assign(this,{dimension:null,noise:null,clusters:null,factory:null,shape:null,density:null,settings:null,surface:null,structures:null,placement:null,registry:null,native:null,terrain:null,layoutSeed:null,generated:new Set(),queue:[],queued:new Set(),jobs:[],structureJobs:[],structureJobKeys:new Set(),placedStructureKeys:new Set(),state:new Map(),overlap:new StructureOverlapGuard(),descriptorCache:new Map(),nearDescriptorCache:new Map(),shapeCache:new WeakMap(),structureCandidateCache:new Map(),spawnReady:false,spawnTarget:null,lastSaveAt:0,persistenceDirty:false});}
 load(){if(this.noise)return;this.settings=sanitizeSettings(readPackSettings());const rawWorldSeed=world.seed;this.layoutSeed=safeSeed(rawWorldSeed);if(typeof rawWorldSeed!=="bigint"&&!(typeof rawWorldSeed==="number"&&Number.isFinite(rawWorldSeed))&&!(typeof rawWorldSeed==="string"&&/^-?\d+$/.test(rawWorldSeed)))console.warn(`[Sky Archipelago] Invalid world.seed '${rawWorldSeed}', using deterministic fallback seed 0.`);this.dimension=world.getDimension(DIMENSION);this.noise=new IslandNoise(this.layoutSeed);this.clusters=new IslandClusterSampler(this.noise,this.settings);this.factory=new IslandDescriptorFactory(this.noise);this.shape=new IslandShapeSampler(this.noise);this.density=new IslandDensityEvaluator(this.noise,this.shape);this.surface=new ExactSurfacePipeline(this.settings,this.noise);this.structures=new StructureDetection(this.settings);this.placement=new StructurePlacement(this.structures,{generator:this,overlapGuard:this.overlap,terrainOptions:{minY:WORLD_MIN_Y,maxY:WORLD_MAX_Y}});this.registry=new StructureRegistry();this.registry.refresh();this.overlap.load();this.terrain=new TerrainAdaptationEngine(this.dimension,{minY:WORLD_MIN_Y,maxY:WORLD_MAX_Y});this.native=new NativeStructureCoordinator(this,this.dimension,this.overlap);try{const raw=world.getDynamicProperty(DB);if(typeof raw==="string"){const d=JSON.parse(raw);if(d.seed===this.layoutSeed.toString()&&d.settingsHash===this.settingsHash()){this.generated=new Set(d.generated||[]);this.placedStructureKeys=new Set(d.placedStructureKeys||[]);this.state=new Map(d.state||[]);this.structureJobs=d.structureJobs||[];this.structureJobKeys=new Set(this.structureJobs.map(j=>j.key));this.spawnTarget=d.spawnTarget??null;this.spawnReady=Boolean(this.spawnTarget);}}}catch(e){console.warn(`[Sky Archipelago] persistence load failed: ${e}`);}for(const[k,v]of this.state)if(v!=="COMPLETE"&&!this.queued.has(k)){const[cx,cz]=k.split(",").map(Number);if(Number.isFinite(cx)&&Number.isFinite(cz)){this.queued.add(k);this.queue.push({cx,cz});}}}
 settingsHash(){return JSON.stringify(this.settings);}
 save(force=false){const now=Date.now();if(!force&&(now-this.lastSaveAt<MAX_PERSISTENCE_RETRY_MS))return;if(this.layoutSeed===null)return;const generated=[...this.generated].slice(-MAX_PERSISTED_GENERATED),state=[...this.state].slice(-MAX_PERSISTED_STATES),placedStructureKeys=[...this.placedStructureKeys].slice(-MAX_PERSISTED_STRUCTURES),structureJobs=trimArray(this.structureJobs,256);let payload={version:16,seed:this.layoutSeed.toString(),settingsHash:this.settingsHash(),generated,placedStructureKeys,state,structureJobs,spawnTarget:this.spawnTarget};let raw=JSON.stringify(payload);if(raw.length>MAX_DYNAMIC_PROPERTY_LENGTH){payload.structureJobs=[];payload.placedStructureKeys=[];raw=JSON.stringify(payload);}if(raw.length>MAX_DYNAMIC_PROPERTY_LENGTH){payload.state=state.filter(([,v])=>v!=="QUEUED");raw=JSON.stringify(payload);}if(raw.length>MAX_DYNAMIC_PROPERTY_LENGTH){payload.generated=generated.slice(-4000);raw=JSON.stringify(payload);}if(raw.length>MAX_DYNAMIC_PROPERTY_LENGTH){console.warn(`[Sky Archipelago] persistence payload remains too large (${raw.length}); skipping save rather than throwing.`);return;}try{world.setDynamicProperty(DB,raw);this.lastSaveAt=now;this.persistenceDirty=false;}catch(e){console.warn(`[Sky Archipelago] persistence save failed (${raw.length}/${MAX_DYNAMIC_PROPERTY_LENGTH}): ${e}`);}}
 cluster(cx,cz){cx=finite(cx,0);cz=finite(cz,0);return this.clusters.cluster(cx,cz,this.layoutSeed,this.settings.spacing);}
 descriptorsForCell(cx,cz){cx=finite(cx,0);cz=finite(cz,0);const key=`${cx},${cz}`,cached=this.descriptorCache.get(key);if(cached)return cached;const c=this.cluster(cx,cz),out=[this.factory.anchor(c)];for(let i=0;i<c.satelliteCount;i++)out.push(this.factory.satellite(c,i));for(let i=0;i<c.spireCount;i++)out.push(this.factory.spire(c,i));const scale=Math.max(.35,Math.min(2.2,(this.settings.minIslandRadius/18+this.settings.maxIslandRadius/72)/2)),ss=this.settings.spacing/96;for(const d of out){d.x=finite(d.x,c.centerX);d.z=finite(d.z,c.centerZ);d.rx=positive(d.rx,this.settings.minIslandRadius);d.rz=positive(d.rz,this.settings.minIslandRadius);d.maxR=Math.max(d.rx,d.rz);d.plateau=finite(d.plateau,this.settings.minIslandY)*this.settings.terrainReliefScale;d.cliff=Math.max(4,finite(d.cliff,16)*this.settings.terrainReliefScale);d.hang=Math.max(8,Math.min(this.settings.maxIslandThickness,finite(d.hang,32)));d.x=c.centerX+(d.x-c.centerX)*ss;d.z=c.centerZ+(d.z-c.centerZ)*ss;d.rx=Math.max(4,d.rx*scale);d.rz=Math.max(4,d.rz*scale);d.maxR=Math.max(d.rx,d.rz);}this.descriptorCache.set(key,out);return out;}
 descriptorsNear(x,z){x=finite(x,0);z=finite(z,0);const s=positive(this.settings.spacing,96),cx=Math.floor(x/s),cz=Math.floor(z/s),key=`${x},${z}`,cached=boundedGetCache(this.nearDescriptorCache,key);if(cached)return cached;const out=[];for(let ix=cx-3;ix<=cx+3;ix++)for(let iz=cz-3;iz<=cz+3;iz++)for(const d of this.descriptorsForCell(ix,iz)){const reach=Math.max(d.maxR*3+96,Math.max(Math.abs(finite(d.hangX,0))+finite(d.tailX,0)*2,Math.abs(finite(d.hangZ,0))+finite(d.tailZ,0)*2)+96),dx=x-d.x,dz=z-d.z;if(dx*dx+dz*dz<=reach*reach)out.push(d);}return boundedSetCache(this.nearDescriptorCache,key,out,MAX_NEAR_DESCRIPTOR_CACHE);}
 shapeSample(d,x,z){x=finite(x,0);z=finite(z,0);let cache=this.shapeCache.get(d);if(!cache){cache=new Map();this.shapeCache.set(d,cache);}const key=`${x},${z}`,cached=cache.get(key);if(cached)return cached;const h=this.shape.sample(d,x,z);cache.set(key,h);return h;}
 column(x,z,minY=WORLD_MIN_Y,maxY=WORLD_MAX_Y){const ds=this.descriptorsNear(x,z);if(!ds.length)return[];const prepared=[];let scanMin=maxY,scanMax=minY;for(const d of ds){const h=this.shapeSample(d,x,z);if(!h.influence)continue;prepared.push({d,h});const low=Math.max(minY,Math.floor(d.y-d.cliff-d.hang-96)),high=Math.min(maxY,Math.ceil(d.y+d.plateau+96));if(low<scanMin)scanMin=low;if(high>scanMax)scanMax=high;}if(!prepared.length)return[];const raw=[];let active=false,top=0;for(let y=scanMax-1;y>=scanMin;y--){let den=-Infinity;for(const p of prepared)den=Math.max(den,this.density.density(p.d,p.h,x,y,z));const solid=den>0;if(solid&&!active){top=y;active=true;}if(!solid&&active){raw.push([y+1,top]);active=false;}}if(active)raw.push([scanMin,top]);return this.resolveOverlapExact(raw);}
 resolveOverlapExact(raw){if(raw.length<2)return raw;const mode=this.settings.terrainOverlapMode;if(mode==="overlap")return raw;if(mode==="void")return[raw.reduce((a,b)=>a[1]>b[1]?a:b)];const sorted=[...raw].sort((a,b)=>b[1]-a[1]),keep=[sorted[0]];for(let i=1;i<sorted.length;i++){const lower=sorted[i],upper=keep[keep.length-1],gap=upper[0]-lower[1];if(gap>=8){const carving=Math.min(28,Math.max(2,Math.floor((upper[1]-upper[0]+1)*.5))),end=lower[1]-carving;if(end-lower[0]+1>=4)keep.push([lower[0],end]);}}return keep.sort((a,b)=>a[0]-b[0]);}
 biomeAt(dim,x,y,z){try{return dim.getBiome({x,y,z})?.id??"minecraft:plains";}catch{return"minecraft:plains";}}
 generateColumn(dim,x,z,segments){if(!segments.length)return;const top=Math.max(...segments.map(s=>s[1])),biome=this.biomeAt(dim,x,top,z),profile=terrainProfile(biome),plan=planColumn(segments,WORLD_MIN_Y,WORLD_MAX_Y+1,{...this.settings,deepslateStartY:this.settings.deepslateStartY-(profile[0]-1)*3},x,z,this.layoutSeed);for(let y=WORLD_MIN_Y;y<=WORLD_MAX_Y;y++){const p=plan.materialAt(y);if(p)dim.setBlockPermutation({x,y,z},p);else if(this.settings.oceanEnabled&&y<=plan.oceanTop&&y>top)dim.setBlockType({x,y,z},WATER);else if(y>=top+1)dim.setBlockType({x,y,z},"minecraft:air");}this.surface.apply(dim,x,z,segments,biome,profile,this.layoutSeed);}
 findSpawnDescriptor(){const c=this.cluster(0,0),ds=this.descriptorsForCell(0,0);return ds[0]??this.factory.anchor(c);}
 spawnSurface(d){const points=[[finite(d.x,0),finite(d.z,0)],[finite(d.x,0)+Math.min(8,positive(d.rx,16)*.25),finite(d.z,0)],[finite(d.x,0)-Math.min(8,positive(d.rx,16)*.25),finite(d.z,0)],[finite(d.x,0),finite(d.z,0)+Math.min(8,positive(d.rz,16)*.25)],[finite(d.x,0),finite(d.z,0)-Math.min(8,positive(d.rz,16)*.25)]];let best=null;for(const[x,z]of points){const h=this.shapeSample(d,x,z);if(!h?.influence)continue;let top=Math.min(WORLD_MAX_Y,Math.ceil(finite(d.y,this.settings.minIslandY)+finite(d.plateau,0)+96)),bottom=Math.max(WORLD_MIN_Y,Math.floor(finite(d.y,this.settings.minIslandY)-finite(d.cliff,16)-finite(d.hang,32)-96));for(let y=top;y>=bottom;y--)if(this.density.density(d,h,x,y,z)>0){if(!best||y>best.y)best={x:Math.floor(x),y,z:Math.floor(z)};break;}}return best;}
 ensureSpawnIsland(){this.load();if(this.spawnReady&&this.spawnTarget)return this.spawnTarget;const d=this.findSpawnDescriptor();if(!d)throw new Error("Deterministic spawn anchor descriptor is missing");for(const k of ["x","z","y","rx","rz","plateau","cliff","hang"]){if(!Number.isFinite(Number(d[k])))console.warn(`[Sky Archipelago] Spawn descriptor field ${k} is invalid (${d[k]}); applying safe fallback.`);}const p=this.spawnSurface(d);if(!p)throw new Error("Deterministic spawn anchor did not produce a valid island surface");this.spawnTarget={x:p.x,y:p.y,z:p.z};this.spawnReady=true;const cx=Math.floor(p.x/16),cz=Math.floor(p.z/16);for(let dx=-SPAWN_RADIUS_CHUNKS;dx<=SPAWN_RADIUS_CHUNKS;dx++)for(let dz=-SPAWN_RADIUS_CHUNKS;dz<=SPAWN_RADIUS_CHUNKS;dz++)this.enqueue(cx+dx,cz+dz);this.queue.sort((a,b)=>((a.cx-cx)**2+(a.cz-cz)**2)-((b.cx-cx)**2+(b.cz-cz)**2));this.queueStructuresForChunk(cx,cz);this.save(true);return this.spawnTarget;}
 structureSeed(x,z,type="structure"){x=finite(x,0);z=finite(z,0);let v=this.layoutSeed^BigInt(Math.trunc(x)*0x9E3779B1)^BigInt(Math.trunc(z)*0x85EBCA77);for(const c of String(type))v^=BigInt(c.charCodeAt(0));v^=v>>33n;v*=0xff51afd7ed558ccdn;v^=v>>33n;return Number(v&0x7fffffffn)/0x80000000;}
 enqueue(cx,cz){const k=`${cx},${cz}`;if(this.generated.has(k)||this.queued.has(k))return;this.queued.add(k);this.state.set(k,"QUEUED");this.queue.push({cx,cz});}
 requestAround(player){this.load();const cx=Math.floor(finite(player.location.x,0)/16),cz=Math.floor(finite(player.location.z,0)/16);for(let dx=-8;dx<=8;dx++)for(let dz=-8;dz<=8;dz++)this.enqueue(cx+dx,cz+dz);this.queue.sort((a,b)=>((a.cx-cx)**2+(a.cz-cz)**2)-((b.cx-cx)**2+(b.cz-cz)**2));this.queueStructuresForChunk(cx,cz);this.persistenceDirty=true;this.save();}
 startNext(){if(this.jobs.length||!this.queue.length)return;const q=this.queue.shift(),k=`${q.cx},${q.cz}`;this.state.set(k,"GENERATING");this.jobs.push({cx:q.cx,cz:q.cz,x:0,z:0});this.persistenceDirty=true;this.save();}
 tick(){this.load();this.placeQueuedStructures();this.startNext();const j=this.jobs[0];if(!j)return;const dim=this.dimension??world.getDimension(DIMENSION),start=Date.now(),budget=4;let count=0;while(count<16&&j.x<16&&Date.now()-start<budget){this.generateColumn(dim,j.cx*16+j.x,j.cz*16+j.z,this.column(j.cx*16+j.x,j.cz*16+j.z));j.z++;count++;if(j.z>=16){j.z=0;j.x++;}}if(j.x>=16){const k=`${j.cx},${j.cz}`;this.generated.add(k);this.queued.delete(k);this.state.set(k,"COMPLETE");this.jobs.shift();this.persistenceDirty=true;this.save();}}
 reset(){this.generated.clear();this.queue=[];this.queued.clear();this.jobs=[];this.structureJobs=[];this.structureJobKeys.clear();this.placedStructureKeys.clear();this.state.clear();this.descriptorCache.clear();this.nearDescriptorCache.clear();this.structureCandidateCache.clear();this.overlap.clear();this.spawnReady=false;this.spawnTarget=null;this.persistenceDirty=true;this.save(true);}}
