import { SkyIslandConfig } from "../config/SkyIslandConfig.js";
export const Archetype=Object.freeze({CLASSIC:"classic",BOWL_CRATER:"bowl_crater",CRESCENT:"crescent",TERRACE:"terrace"});
export const Family=Object.freeze({ANCHOR:"anchor",SATELLITE:"satellite",SPIRE:"spire"});
const config=new SkyIslandConfig();
export class IslandClusterSampler{
 constructor(noise){this.noise=noise;this.settings=null;}
 get s(){if(!this.settings)this.settings=config.load();return this.settings;}
 heightBand(cx,cz){const s=this.s,t=s.lowWeight+s.midHighWeight+s.veryHighWeight;let r=this.noise.sampleCell(cx,cz,240)*t;if(r<s.lowWeight)return"low";r-=s.lowWeight;return r<s.midHighWeight?"mid_high":"very_high";}
 heightProfile(b){const s=this.s,min=s.minIslandY,max=s.maxIslandY,span=Math.max(24,max-min),lw=Math.max(12,span/5),hw=Math.max(12,span/6),midMin=min+Math.max(12,span/5),midMax=max-Math.max(12,span/6),lc=Math.max(min+lw/2,Math.min(midMin-8,min+Math.max(10,span/6)+s.lowOffset)),hc=Math.min(max-hw/2,Math.max(midMax+8,max-Math.max(8,span/9)+s.veryHighOffset));if(b==="low")return[min,Math.min(max,Math.max(min+8,lc+lw/2))];if(b==="mid_high")return[Math.max(min,Math.min(midMin,lc+lw/2+4)),Math.min(max,Math.max(min+12,Math.max(midMax,hc-hw/2-4)))];return[Math.max(min,Math.min(max-8,hc-hw/2)),max];}
 cluster(cx,cz,seed,spacing){const s=this.s,half=spacing/2,jitter=Math.max(10,spacing/3),band=this.heightBand(cx,cz),[minY,maxY]=this.heightProfile(band),centerX=cx*spacing+half+this.noise.sampleCellInt(cx,cz,163,-jitter,jitter),centerZ=cz*spacing+half+this.noise.sampleCellInt(cx,cz,197,-jitter,jitter),centerY=this.noise.sampleCellInt(cx,cz,223,minY,maxY),tierRoll=this.noise.sampleCell(cx,cz,131),tier=tierRoll<.18?"grand":tierRoll<.72?"standard":"scattered";let sat=tier==="grand"?this.noise.sampleCellInt(cx,cz,281,5,8):tier==="standard"?this.noise.sampleCellInt(cx,cz,281,3,6):this.noise.sampleCellInt(cx,cz,281,2,4);sat+=band==="low"?-1:band==="very_high"&&tier==="grand"?1:0;sat=Math.max(band==="low"?1:2,sat);let sp=tier==="grand"?this.noise.sampleCellInt(cx,cz,307,1,2):this.noise.sampleCellInt(cx,cz,307,0,1);sp+=band==="low"?-1:band==="very_high"?1:0;sp=Math.max(0,Math.min(3,sp));let r=this.noise.sampleCell(cx,cz,463),weights=[s.classicWeight,s.bowlCraterWeight,s.crescentWeight,s.terraceWeight],sum=weights.reduce((a,b)=>a+b,0),target=r*sum,arch=Archetype.CLASSIC;for(const[k,w]of Object.entries({classic:weights[0],bowl_crater:weights[1],crescent:weights[2],terrace:weights[3]})){if(target<w){arch=k;break;}target-=w;}return{cx,cz,centerX,centerY,centerZ,band,tier,baseRotation:this.noise.sampleCell(cx,cz,251)*Math.PI*2,archetype:arch,satelliteCount:sat,spireCount:sp,seed:mix(seed,cx,cz)};}
}
function mix(seed,x,z){return BigInt.asIntN(64,BigInt(seed)^BigInt(x)*-7046029254386353131n^BigInt(z)*-4417276706812531889n);}
