import { StructureFootprint } from "./StructurePlacementModel.js";

// A seed-stable piece graph generator. The graph is intentionally engine-agnostic;
// NativeStructureAdapter commits each piece through StructureManager when possible.
export class ProceduralStructureGenerator {
 constructor(seed,adapter){this.seed=BigInt(seed);this.adapter=adapter;}
 rng(x,z,type){let v=this.seed^BigInt(Math.trunc(x))*0x9E3779B97F4A7C15n^BigInt(Math.trunc(z))*0xC2B2AE3D27D4EB4Fn;for(const c of type)v=(v^BigInt(c.charCodeAt(0)))*0x100000001B3n;v^=v>>29n;v*=0x94D049BB133111EBn;v^=v>>31n;return Number(v&0xFFFFFFFFn)/4294967296;}
 stronghold(origin,options={}){const r=this.rng(origin.x,origin.z,"stronghold"),radius=options.radius??32,count=options.pieces??Math.floor(10+r*14),pieces=[];let x=origin.x,z=origin.z,dir=0;pieces.push({type:"start",x,y:origin.y,z,rotation:dir});for(let i=1;i<count;i++){const turn=this.rng(x+i,z-i,"stronghold_piece");if(turn<.35)dir=(dir+(turn<.175?1:3))%4;const len=6+Math.floor(this.rng(x,z+i,"stronghold_len")*10),dx=[1,0,-1,0][dir],dz=[0,1,0,-1][dir];x+=dx*len;z+=dz*len;if(Math.hypot(x-origin.x,z-origin.z)>radius){x=origin.x;z=origin.z;dir=(dir+2)%4;}pieces.push({type:i===count-1?"portal_room":(i%5===0?"library":"corridor"),x,y:origin.y+Math.floor(this.rng(x,z,"stronghold_y")*5)-2,z,rotation:dir});}return{type:"stronghold",origin,pieces,bounds:this.graphBounds(pieces,8,6)};}
 mineshaft(origin,options={}){const r=this.rng(origin.x,origin.z,"mineshaft"),count=options.pieces??Math.floor(12+r*18),pieces=[],nodes=[{x:origin.x,y:origin.y,z:origin.z}];for(let i=0;i<count;i++){const n=nodes[Math.floor(this.rng(origin.x+i,origin.z-i,"node")*nodes.length)],a=this.rng(n.x+i,n.z,"angle"),dir=Math.floor(a*4),len=5+Math.floor(this.rng(n.x,n.z+i,"len")*9),dx=[1,0,-1,0][dir],dz=[0,1,0,-1][dir],p={type:i%9===0?"cross":"corridor",x:n.x+dx*len,y:n.y+Math.floor(this.rng(n.x,n.z,"depth")*5)-2,z:n.z+dz*len,rotation:dir};pieces.push(p);if(pieces.length<64)nodes.push(p);}return{type:"mineshaft",origin,pieces,bounds:this.graphBounds(pieces,5,4)};}
 graphBounds(pieces,w,h){let minX=Infinity,minZ=Infinity,maxX=-Infinity,maxZ=-Infinity,minY=Infinity,maxY=-Infinity;for(const p of pieces){minX=Math.min(minX,p.x-w);maxX=Math.max(maxX,p.x+w);minZ=Math.min(minZ,p.z-w);maxZ=Math.max(maxZ,p.z+w);minY=Math.min(minY,p.y-h);maxY=Math.max(maxY,p.y+h);}return{min:{x:minX,y:minY,z:minZ},max:{x:maxX,y:maxY,z:maxZ}};}
}
