package org.sathrek.sky_archipelago.worldgen.structure.underground;

import org.sathrek.sky_archipelago.worldgen.structure.ResolvedStructureSupportPlane;
import org.sathrek.sky_archipelago.worldgen.structure.StructureFootprint;
import org.sathrek.sky_archipelago.worldgen.structure.sky.SkyStructurePlacementTarget;

public record UndergroundPlacementDecision(
   boolean accepted,
   String rejectionReason,
   boolean searchAttempted,
   boolean moved,
   int candidatesGenerated,
   int candidatesPruned,
   int candidatesEvaluated,
   int samplesEvaluated,
   int worldMinY,
   int maxIslandSpawnY,
   int overburden,
   int depthBelowLocalTop,
   int exposureSamples,
   int supportCount,
   double stoneRatio,
   int verticalDelta,
   int prunedNoColumnAtY,
   int prunedOutsideHostDominance,
   int prunedInsufficientOverburden,
   int prunedInsufficientDepth,
   int prunedInsufficientSupport,
   int prunedInsufficientStone,
   SkyStructurePlacementTarget target,
   StructureFootprint rawFootprint,
   StructureFootprint effectiveFootprint,
   ResolvedStructureSupportPlane supportPlane,
   long anchorSeedKey,
   int anchorX,
   int anchorZ,
   String hostFamily,
   int hostX,
   int hostY,
   int hostZ,
   int hostRadius,
   String rankMetrics,
   String tieBreakPath
) {
   public static UndergroundPlacementDecision rejected(
      String reason,
      StructureFootprint rawFootprint,
      StructureFootprint effectiveFootprint,
      ResolvedStructureSupportPlane supportPlane,
      long anchorSeedKey,
      int anchorX,
      int anchorZ,
      int candidatesGenerated,
      int candidatesPruned,
      int candidatesEvaluated,
      int worldMinY,
      int maxIslandSpawnY,
      int prunedNoColumnAtY,
      int prunedOutsideHostDominance,
      int prunedInsufficientOverburden,
      int prunedInsufficientDepth,
      int prunedInsufficientSupport,
      int prunedInsufficientStone,
      String hostFamily,
      int hostX,
      int hostY,
      int hostZ,
      int hostRadius
   ) {
      return new UndergroundPlacementDecision(
         false,
         reason,
         true,
         false,
         candidatesGenerated,
         candidatesPruned,
         candidatesEvaluated,
         0,
         worldMinY,
         maxIslandSpawnY,
         0,
         0,
         0,
         0,
         0.0,
         0,
         prunedNoColumnAtY,
         prunedOutsideHostDominance,
         prunedInsufficientOverburden,
         prunedInsufficientDepth,
         prunedInsufficientSupport,
         prunedInsufficientStone,
         null,
         rawFootprint,
         effectiveFootprint,
         supportPlane,
         anchorSeedKey,
         anchorX,
         anchorZ,
         hostFamily,
         hostX,
         hostY,
         hostZ,
         hostRadius,
         "none",
         "valid>score>move>spatial>structure"
      );
   }
}
