package org.sathrek.sky_archipelago.worldgen.structure.mineshafts;

import org.sathrek.sky_archipelago.worldgen.structure.sky.SkyStructurePlacementTarget;

public record MineshaftPlacementDecision(
   boolean accepted,
   String rejectionReason,
   boolean searchAttempted,
   boolean moved,
   int candidatesGenerated,
   int candidatesPruned,
   int candidatesEvaluated,
   int samplesEvaluated,
   int overburden,
   int supportCount,
   double stoneRatio,
   int verticalDelta,
   String anchorSource,
   int anchorBaseY,
   int worldMinY,
   int maxIslandSpawnY,
   int effectiveMinY,
   int effectiveMaxY,
   int hostMultiplierCap,
   int prunedNoColumnAtY,
   int prunedOutsideHostDominance,
   int prunedInsufficientOverburden,
   int prunedInsufficientSupport,
   int prunedInsufficientStone,
   String earlyStopReason,
   SkyStructurePlacementTarget target,
   long anchorSeedKey,
   int anchorX,
   int anchorZ,
   String hostFamily,
   int hostX,
   int hostY,
   int hostZ,
   int hostRadius,
   String rankMetrics,
   String tieBreakPath
) {
   public static MineshaftPlacementDecision rejected(
      String reason,
      String anchorSource,
      int anchorBaseY,
      int worldMinY,
      int maxIslandSpawnY,
      int effectiveMinY,
      int effectiveMaxY,
      int hostMultiplierCap,
      long anchorSeedKey,
      int anchorX,
      int anchorZ,
      int candidatesGenerated,
      int candidatesPruned,
      int candidatesEvaluated,
      int samplesEvaluated,
      int prunedNoColumnAtY,
      int prunedOutsideHostDominance,
      int prunedInsufficientOverburden,
      int prunedInsufficientSupport,
      int prunedInsufficientStone,
      String earlyStopReason,
      String hostFamily,
      int hostX,
      int hostY,
      int hostZ,
      int hostRadius
   ) {
      return new MineshaftPlacementDecision(
         false,
         reason,
         true,
         false,
         candidatesGenerated,
         candidatesPruned,
         candidatesEvaluated,
         samplesEvaluated,
         0,
         0,
         0.0,
         0,
         anchorSource,
         anchorBaseY,
         worldMinY,
         maxIslandSpawnY,
         effectiveMinY,
         effectiveMaxY,
         hostMultiplierCap,
         prunedNoColumnAtY,
         prunedOutsideHostDominance,
         prunedInsufficientOverburden,
         prunedInsufficientSupport,
         prunedInsufficientStone,
         earlyStopReason,
         null,
         anchorSeedKey,
         anchorX,
         anchorZ,
         hostFamily,
         hostX,
         hostY,
         hostZ,
         hostRadius,
         "none",
         "valid>score>move>spatial>structure"
      );
   }
}
