#!/usr/bin/env python3
"""Convert the importer JSON artifacts into a Bedrock-loadable JS module.

Bedrock Script modules are JavaScript modules; the runtime should not depend on
Node's filesystem APIs or assume JSON module import assertions are supported.
This tool takes the generated jigsaw-data.json and emits generated/jigsaw-data.js.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="bedrock-addon/scripts/worldgen/generated/jigsaw-data.json")
    parser.add_argument("--output", default="bedrock-addon/scripts/worldgen/generated/jigsaw-data.js")
    args = parser.parse_args()

    source = Path(args.input).resolve()
    output = Path(args.output).resolve()
    if not source.exists():
        raise SystemExit(f"Generated JSON does not exist: {source}")

    data = json.loads(source.read_text(encoding="utf-8"))
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"), allow_nan=False)

    text = f'''/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Source: {source.name}
 * Generated by tools/emit_jigsaw_runtime_data.py
 */
const GENERATED_JIGSAW_DATA = {payload};

export default GENERATED_JIGSAW_DATA;
export {{ GENERATED_JIGSAW_DATA }};
'''

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"Wrote runtime jigsaw module: {output}")
    print(f"Schema version: {data.get('schema_version', 'unknown')}")
    print(f"Pieces: {len(data.get('pieces', {}))}")
    print(f"Pools: {len(data.get('template_pools', {}))}")
    print(f"Structures: {len(data.get('structures', {}))}")
    print(f"Processors: {len(data.get('processors', {}))}")
    print(f"Structure sets: {len(data.get('structure_sets', {}))}")


if __name__ == "__main__":
    main()
