#!/usr/bin/env python3
"""Emit the complete generated-JS runtime database used by the Bedrock port.

The JS database is intentionally richer than a plain JSON mirror.  It is the
single runtime-facing artifact consumed by Script API.  The source JSON may
contain native-worldgen definitions, resolved template metadata, aliases,
missing-file diagnostics, processor lists, structure sets, connector indexes,
and compatibility information.  Everything is serialized into one static JS
module so the addon never needs Node/fs or JSON module assertions at runtime.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def normalize(data: dict[str, Any]) -> dict[str, Any]:
    out = dict(data)
    out.setdefault("schema_version", 1)
    out.setdefault("template_pools", out.get("pools", {}))
    out.setdefault("structures", out.get("jigsaw_structures", {}))
    out.setdefault("jigsaw_structures", out.get("structures", {}))
    out.setdefault("processors", {})
    out.setdefault("structure_sets", out.get("structureSets", {}))
    out.setdefault("pieces", {})
    out.setdefault("resolved_templates", {})
    out.setdefault("template_aliases", {})
    out.setdefault("connectors", out.get("jigsaw_connectors", {}))
    out.setdefault("generated_files", {})
    out.setdefault("native", {})
    out.setdefault("metadata", {})
    out.setdefault("missing_templates", out.get("missing", []))
    out.setdefault("missing_by_reason", {})

    # Build compact reverse indexes once. These make the JS runtime much more
    # useful without repeatedly walking thousands of pieces at runtime.
    reverse = {}
    for identifier, path in out.get("resolved_templates", {}).items():
        if isinstance(path, str):
            reverse[path.replace("\\", "/")] = identifier
    out["resolved_path_index"] = reverse

    structure_by_pool = {}
    for identifier, definition in out.get("structures", {}).items():
        if not isinstance(definition, dict):
            continue
        definition = definition.get("definition", definition)
        if isinstance(definition, dict) and definition.get("start_pool"):
            structure_by_pool.setdefault(definition["start_pool"], []).append(identifier)
    out["structures_by_start_pool"] = structure_by_pool

    pool_users = {}
    for identifier, definition in out.get("template_pools", {}).items():
        definition = definition.get("definition", definition) if isinstance(definition, dict) else definition
        for element in definition.get("elements", []) if isinstance(definition, dict) else []:
            element = element.get("element", element) if isinstance(element, dict) else element
            if isinstance(element, dict) and element.get("location"):
                pool_users.setdefault(element["location"], []).append(identifier)
    out["pools_by_template"] = pool_users

    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="bedrock-addon/scripts/worldgen/generated/jigsaw-data.json")
    parser.add_argument("--output", default="bedrock-addon/scripts/worldgen/generated/jigsaw-data.js")
    args = parser.parse_args()

    source = Path(args.input).resolve()
    output = Path(args.output).resolve()
    if not source.exists():
        raise SystemExit(f"Generated JSON does not exist: {source}")

    data = normalize(json.loads(source.read_text(encoding="utf-8")))
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"), allow_nan=False)

    text = f'''/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Source: {source.name}
 * Generated by tools/emit_jigsaw_runtime_data.py
 *
 * This module is the complete runtime metadata database for the Bedrock
 * Script API implementation. It deliberately contains native-worldgen
 * definitions as metadata so JS can prefer native placement and only fall
 * back to emulation when Bedrock cannot express a feature.
 */
const GENERATED_JIGSAW_DATA = {payload};

export default GENERATED_JIGSAW_DATA;
export {{ GENERATED_JIGSAW_DATA }};
'''

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"Wrote runtime jigsaw module: {{output}}")
    print(f"Schema version: {{data.get('schema_version', 'unknown')}}")
    print(f"Pieces: {{len(data.get('pieces', {{}}))}}")
    print(f"Pools: {{len(data.get('template_pools', {{}}))}}")
    print(f"Structures: {{len(data.get('structures', {{}}))}}")
    print(f"Processors: {{len(data.get('processors', {{}}))}}")
    print(f"Structure sets: {{len(data.get('structure_sets', {{}}))}}")
    print(f"Resolved templates: {{len(data.get('resolved_templates', {{}}))}}")
    print(f"Missing templates: {{len(data.get('missing_templates', []))}}")
    print(f"Native metadata kinds: {{len(data.get('native', {{}}))}}")


if __name__ == "__main__":
    main()
